<div id="whis">
	        	<p class="whis">
	        		Přejeme Vám příjemné posezení a dobrou chuť.
	        	</p>
	        	<p class="whis2">
	        	    Máte zájem oslavit u nás významnou rodinnou událost, uspořádat pracovní schůzku, raut či svatební hostinu ?
	        	</p>
	        	<p>
	        	    Obraťte se laskavě na náš personál, který Vám rád poskytne veškeré informace. <br /> 
	        	    Nabízíme Vám denní menu a jídla na objednávku. V případě zájmu připravíme také snídani. 
	        	</p>
	        </div>