<h1> Upravit produkt </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="">Upravit produkt</li>
	<li class="active"><strong><?php echo $this->allItems->title['cz']?></strong></li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">	
		
			<div class="panel panel-default">
			  <div class="panel-heading">Menu</div>			
			  <ul class="menu list-group">
			  	<?php foreach ($this->subLinks as $val){?>
			    	<li class="list-group-item <?php if($this->sublinkTitle == $val['title']) echo "selected";?> <?php if($this->showOnlyMainSublink && !$val['isMain']) echo "disabled";?>" <?php if($this->showOnlyMainSublink && !$val['isMain']){?> data-toggle="tooltip" data-placement="right" title="Nejprve uložte základní údaje" <?php }?>>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?><a href="<?php echo $val['url'];?>"><?php }?>
			    			<?php echo $val['title'];?>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?></a><?php }?>
			    	</li>
			  	<?php }?>
			  </ul>
			</div>
		</div>	
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">Ceny</div>
				
				<div class="panel-body">
					 <div class="form-group has-feedback">	
					    <label for="parent">Cena nyní:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
						    	<div class="input-group">
						    		<input class="form-control" id="title" type="number" step="any" name="price-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->price[$val->suffix])echo $this->allItems->price[$val->suffix];?>" />
						    		<div class="input-group-addon"><?php echo $val->currencySign;?></div>
						    	</div>
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
					<div class="form-group has-feedback">	
					    <label>Původní cena:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
						    	<div class="input-group">
							    	<input class="form-control" id="title" type="number" step="any" name="originalPrice-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->originalPrice[$val->suffix])echo $this->allItems->originalPrice[$val->suffix];?>" />
						    		<div class="input-group-addon"><?php echo $val->currencySign;?></div>
						    	</div>
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>				    
			       	<div class="checkbox row">
					    <label class="no-padding-left col-xs-4"><strong>Text před cenou nyní:</strong></label>	
			       		<label class="radio-inline"> <input type="checkbox" value="Od" name="priceTextBefore" class="checkbox" <?PHP if($this->allItems->priceTextBefore == "Od")echo "checked='checked'"; ?>>Od </label>
			       	</div>
				</div>	
			</div>		
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-block btn-primary check-required-fields check-category-selected" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
</form>	
	
