<h1> Upravit produkt </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="">Upravit produkt</li>
	<li class="active"><strong><?php echo $this->allItems->title['cz']?></strong></li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">	
		
			<div class="panel panel-default">
			  <div class="panel-heading">Menu</div>			
			  <ul class="menu list-group">
			  	<?php foreach ($this->subLinks as $val){?>
			    	<li class="list-group-item <?php if($this->sublinkTitle == $val['title']) echo "selected";?> <?php if($this->showOnlyMainSublink && !$val['isMain']) echo "disabled";?>" <?php if($this->showOnlyMainSublink && !$val['isMain']){?> data-toggle="tooltip" data-placement="right" title="Nejprve uložte základní údaje" <?php }?>>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?><a href="<?php echo $val['url'];?>"><?php }?>
			    			<?php echo $val['title'];?>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?></a><?php }?>
			    	</li>
			  	<?php }?>
			  </ul>
			</div>
		</div>	
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="row">
						<div class="col-xs-6 text-with-btn">Seznam vložených kategorií</div>
						<div class="col-xs-6 text-right"><button class="btn btn-success add-product-category" type="button">Přidat kategorii</button></div>
					</div>
				</div>
				
				<div class="panel-body table-responsive">			    
			       	<?php if(!empty($this->allproductCategories)){?>	
						<div class="row">
							<div class="col-xs-12 form-group">
					    		<input type="submit" class="btn btn-danger fileinput-exists" title="smazat označené" value="Smazat označené" name="delete">
					    	</div>
				    	</div>
						<div class="clearfix data-list header">
							<div class="col-sm-3 no-left-padding th">Název kategorie</div>
							<div class="col-sm-3 no-left-padding th">Procenta</div>
							<div class="col-sm-6 text-right th">upravit / smazat</div>		
						</div>
					    <ul class="sortListBasic data-list main-ul productCategory">
							<?php foreach($this->allproductCategories as $val){ ?>
							        <li class="clearfix" id="<?php echo $val->productCategoryID ?>">               
										<div class="col-sm-3 first-col text-overflow" ><span class="glyphicons glyphicons-move"></span> <?php echo $val->title; ?></div>
										<div class="col-sm-3 first-col text-overflow" ><?php echo $val->percent; ?>%</div>
										<div class="col-sm-6 text-right">
										    <a title="<?PHP echo $this->translate('Uprav'); ?>" href="" class="edit-product-category"><span class="glyphicons glyphicons-pencil"></span></a>   
										    <input class="delete" type="checkbox" name="deleteProductCategoryID[]" value="<?php echo $val->productCategoryID ?>">
										</div>
										
										<br id="endFloat" />
					                
					                </li>
							<?php } ?>
						</ul>
			       	<?php }else{?>			       	
						<div class="alert alert-warning text-center">
							Zatím nebyla vložena žádná kategorie.
						</div>
			       	<?php }?>
				</div>	
			</div>		
		</div>	
	</div>
	
</form>	
	
<!-- Modal -->
<div class="modal fade" id="addCategory" tabindex="-1" role="dialog" aria-labelledby="addCategoryModal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form method="post" action="<?php echo $this->action;?>">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" class="glyphicons glyphicons-remove"></span></button>
	        <h4 class="modal-title" id="addCategoryModal">Přidat kategorii</h4>
	      </div>
	      <div class="modal-body">
		        <div class="form-group has-feedback">	
				 	<label>*Název kategorie:</label>	    	
				    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
				    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    	<input class="form-control <?php if($val->suffix == "cz")echo "required"; ?>" id="title" type="text" name="title-<?PHP echo $val->suffix ?>" value="<?php if($this->title[$val->suffix])echo $this->title[$val->suffix];?>" />
					    </span>
				    <?PHP $i++; } ?>
					<?php echo $this->render("languageMutations.phtml"); ?>  
			    </div>
		        <div class="form-group has-feedback">	
				 	<label>Procentuální navýšení/snížení ceny:</label>	
				 	<div class="input-group">
					    <input class="form-control" id="title" type="number" step="any" name="percent" value="<?php if($this->percent)echo $this->percent;?>" />
					    <div class="input-group-addon">%</div>
			    	</div>    	
				</div>
			    <div class="form-group">	
			    	<label>Text:</label>
					<?php echo $this->render("languageMutations.phtml"); ?>  
				    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
				    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    		<textarea id="text-<?PHP echo $val->suffix ?>" class="basic form-control" placeholder="Text" name="text-<?PHP echo $val->suffix ?>"><?php if($this->text[$val->suffix])echo $this->text[$val->suffix]; ?></textarea>
				    		<script>execTinyMCE(0,'text-<?PHP echo $val->suffix ?>');</script>
					    </span>
				    <?PHP $i++; } ?>	    	
			    </div>
			    <div class="form-group row">
			    	<div class="col-sm-8"><strong>Přiřadit potahy:</strong></div>
			    	<div class="row">
				    	<div class="col-xs-12">
					    	<?php foreach ($this->allCovers as $val){?>
					    		<div class="col-sm-3">
					    			<label class="checkbox-inline" style="font-size: 12px;">
					    				<input class="checkbox" type="checkbox" name="coverID[]" value="<?php echo $val->coverID?>"> 
					    				<?php echo $val->title?>
					    			</label>
					    		</div>
					    	<?php }?>
				    	</div>
			    	</div>
			    </div>
			    <input type="hidden" name="productCategoryID" value="0" />
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Zrušit</button>
	        <input type="submit" class="btn btn-primary check-required-fields" value="Přidat" name="enter" />
	      </div>
	  </form>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="editCategory" tabindex="-1" role="dialog" aria-labelledby="editCategoryModal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <form method="post" action="<?php echo $this->action;?>">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" class="glyphicons glyphicons-remove"></span></button>
	        <h4 class="modal-title" id="editCategoryModal">Upravit kategorii</h4>
	      </div>
	      <div class="modal-body">
		        
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Zrušit</button>
	        <input type="submit" class="btn btn-primary check-required-fields" value="Upravit" name="enter" />
	      </div>
	  </form>
    </div>
  </div>
</div>