<h1> Upravit produkt </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="">Upravit produkt</li>
	<li class="active"><strong><?php echo $this->allItems->title['cz']?></strong></li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">	
		
			<div class="panel panel-default">
			  <div class="panel-heading">Menu</div>			
			  <ul class="menu list-group">
			  	<?php foreach ($this->subLinks as $val){?>
			    	<li class="list-group-item <?php if($this->sublinkTitle == $val['title']) echo "selected";?> <?php if($this->showOnlyMainSublink && !$val['isMain']) echo "disabled";?>" <?php if($this->showOnlyMainSublink && !$val['isMain']){?> data-toggle="tooltip" data-placement="right" title="Nejprve uložte základní údaje" <?php }?>>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?><a href="<?php echo $val['url'];?>"><?php }?>
			    			<?php echo $val['title'];?>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?></a><?php }?>
			    	</li>
			  	<?php }?>
			  </ul>
			</div>
		</div>	
		<div class="col-md-8">
    
			<div class="panel panel-default">
				<div class="panel-heading">Obecná velikost</div>				
				<div class="panel-body">					
					<div class="form-group">	
						<p class="help-block">Obecná velikost produktu slouží pro fitr ve vyhledávání produktů.</p>
				    	<label>Obecná velikost produktu:</label>							    	
					    <select name="productGeneralSizeID" class="form-control required">
					    	<option value="1" <?php if($this->allItems->productGeneralSizeID == 1)echo "selected='selected'"?>>nespecifikováno</option>					    		
					    	<option value="2" <?php if($this->allItems->productGeneralSizeID == 2)echo "selected='selected'"?>>malý</option>
					    	<option value="3" <?php if($this->allItems->productGeneralSizeID == 3)echo "selected='selected'"?>>střední</option>
					    	<option value="4" <?php if($this->allItems->productGeneralSizeID == 4)echo "selected='selected'"?>>velký</option>
					    </select>  	
				    </div>	
				</div>	
			</div>
			<div class="panel panel-default">
				<div class="panel-heading">Rozměry</div>
				
				<div class="panel-body">	
					<?php foreach ($this->allTypes as $val){?>
						<div class="col-sm-6 no-padding-left no-padding-right text-center product-size-wrapper">
							<div class="form-group checkbox">
								<label>
									<input class="radio-inline" type="checkbox" name="productTypeID" value="<?php echo $val->productTypeID?>" <?php if($this->allItems->productTypeID == $val->productTypeID) echo "checked"?>> <?php echo $val->title?>
							 	</label>
							 </div>
							<span class="product-size">
								<img src="/Public/Images/ProductSizes/<?php echo $val->photo?>" />
								<?php foreach ($val->numberPositions as $position){?>
									<input type="text" value="<?php if(isset($this->allProductSizesArr[$val->productTypeID][$position->productSizeNumberPositionID])) echo $this->allProductSizesArr[$val->productTypeID][$position->productSizeNumberPositionID];?>" class="product-size-number" name="<?php echo $position->productSizeNumberPositionID ?>-productSizeNumberPositionID" style="position: absolute; left: <?php echo $position->x?>%; top: <?php echo $position->y?>%;width:40px;">
								<?php }?>
							</span>
						</div>
					<?php }?>
				</div>	
			</div>	
			<div class="panel panel-default">
				<div class="panel-heading">Popis</div>
				
				<div class="panel-body">	
					
					<div class="form-group">	
				    	<label>Popis k rozměrům:</label>
						<?php echo $this->render("languageMutations.phtml"); ?>  
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    		<textarea id="textSize-<?PHP echo $val->suffix ?>" class="basic form-control" placeholder="Text" name="textSize-<?PHP echo $val->suffix ?>"><?php if($this->allItems->textSize[$val->suffix])echo $this->allItems->textSize[$val->suffix]; ?></textarea>
					    		<script>execTinyMCE(0,'textSize-<?PHP echo $val->suffix ?>');</script>
						    </span>
					    <?PHP $i++; } ?>	    	
				    </div>	
				</div>	
			</div>
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-block btn-primary check-required-fields check-category-selected" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
</form>	
	
