<h1> Seznam produktů </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="active">Seznam produktů</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">
	<div class="panel panel-default">		
		<div class="panel-heading clearfix">
				<div class="row">
					<div class="col-sm-6">
						<a class="btn btn-sm btn-success delButton" href="/admin/eshop/produkt/pridat"> Přidat nový produkt </a>
					</div>
					<div class="text-right col-sm-6">
						<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
					</div>
				</div>
			
		</div>
		<div class="panel-body table-responsive" id="products">
			
			<div class="filters row">
				<div class="col-sm-12">
					<div class="form-inline">
						<div class="form-group">
					  		<input class="search form-control" placeholder="Vyhledat..." />
						</div>					  
						<div class="form-group">
						 	 <label >Zobrazit:</label>
							  <select class="form-control" id="category-filter">
							  	<option value="" class="0">-- Kategorii --</option>
							  	<?php foreach($this->allCategories as $val){?>
							  		<option value="<?php echo $val->title?>" class="<?php echo $val->linkID;?>"><?php echo $val->title?></option>
							  	<?php }?>
							  </select>
						</div>				  
						<div class="form-group">
						 	 <label >Podkategorii:</label>
							  <select class="form-control" id="subcategory-filter">
							  	<option value="">-- Podkategorii --</option>
							  </select>
						</div>
					 </div>
				 </div>
			</div>
			
			<div class="clearfix data-list header">
				<div class="col-sm-3 no-left-padding th">Název produktu</div>
				<div class="col-sm-3 th text-center">Kategorie</div>
				<div class="col-sm-3 th text-center">Podkategorie</div>
				<div class="col-sm-3 text-right th">upravit / smazat</div>		
			</div>
			
			<?php if(count($this->allItems) > 0){ ?>	
			    <ul class="sortListBasic data-list main-ul product list">
					<?php foreach($this->allItems as $val){ ?>
					        <li class="clearfix" id="<?php echo $val->productID ?>">               
								<div class="col-sm-3 first-col text-overflow title" ><span class="glyphicons glyphicons-move"></span> <?php echo $val->title; ?> </div>
								<div class="col-sm-3 text-overflow category text-center" ><?php echo $val->linkTitle; ?></div>
								<div class="col-sm-3 text-overflow subcategory text-center" ><?php echo $val->sublinkTitle; ?></div>
								<div class="col-sm-3 text-right">
								    <a title="<?PHP echo $this->translate('Uprav'); ?>" href="<?php echo $this->baseUrl; ?>/admin/eshop/produkt/upravit/id/<?php echo $val->productID?>"><span class="glyphicons glyphicons-pencil"></span></a>   
								    <input class="delete" type="checkbox" name="delete[]" value="<?php echo $val->productID ?>">
								</div>
								
								<br id="endFloat" />
			                
			                </li>
					<?php } ?>
				</ul>
			<?php }else{ ?>
				<div class="no-data text-center">Zatím se zde nenachází žádný produkt.</div>
			<?php } ?>
			
				
		</div>	
		<div class="panel-footer clearfix">
			
			<div class="text-right">
				<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
				<input type="submit" class ="hidden deleteButton" name="deleteButton" />
			</div>
			
		</div>	
	</div>
</form>