<h1> Upravit produkt </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="">Upravit produkt</li>
	<li class="active"><strong><?php echo $this->allItems->title['cz']?></strong></li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">	
		
			<div class="panel panel-default">
			  <div class="panel-heading">Menu</div>			
			  <ul class="menu list-group">
			  	<?php foreach ($this->subLinks as $val){?>
			    	<li class="list-group-item <?php if($this->sublinkTitle == $val['title']) echo "selected";?> <?php if($this->showOnlyMainSublink && !$val['isMain']) echo "disabled";?>" <?php if($this->showOnlyMainSublink && !$val['isMain']){?> data-toggle="tooltip" data-placement="right" title="Nejprve uložte základní údaje" <?php }?>>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?><a href="<?php echo $val['url'];?>"><?php }?>
			    			<?php echo $val['title'];?>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?></a><?php }?>
			    	</li>
			  	<?php }?>
			  </ul>
			</div>
		</div>	
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">Status a slevy</div>
				
				<div class="panel-body">			    
			       	<div class="form-group clearfix statuses">
					    <div class="clearfix"><label class=""><strong>Status:</strong></label>	</div>
					    <?php foreach ($this->allStatusses as $val){?>
					    	<div class="col-sm-4 item">
					    		<div class="checkbox">
				       				<label> <input type="checkbox" value="<?php echo $val->productStatusID?>" name="productStatusID[]" class="checkbox productStatusID" <?PHP if(!empty($this->allStatussesArr[$val->productStatusID]))echo "checked='checked'"; ?>><?php echo $val->title?> </label>
				       				<div class="additional-options clearfix">
					       				<div class="input-group colorpicker-component" data-toggle="tooltip" title="Podbarvení statusu">
										    <input type="text" value="<?php if(!empty($this->allStatussesArr[$val->productStatusID]) && !empty($this->allStatussesArr[$val->productStatusID]->color))echo $this->allStatussesArr[$val->productStatusID]->color;else echo "#a90c0c"?>" class="form-control" name="<?php echo $val->productStatusID?>-statusColor" />
										    <span class="input-group-addon"><i></i></span>
										</div>
										<div class="priority" data-toggle="tooltip" title="Pořadí zobrazení statusu">
											<input type="number" value="<?php if(!empty($this->allStatussesArr[$val->productStatusID]))echo $this->allStatussesArr[$val->productStatusID]->priority;else echo "0"?>" class="form-control"  name="<?php echo $val->productStatusID?>-statusPriority"/>
										</div>
									</div>
				       			</div>
			       			</div>
			       		<?php }?>
			       	</div>
					 <div class="form-group clearfix">	
				 		<div class="row">
					    	<label class="col-sm-12" for="parent">Výše slevy:</label>	 
					    </div>
				 		<div class="row">
						 	<div class="col-sm-6">   	
							    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
							    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
								    	<div class="input-group">
								    		<input class="form-control" id="title" type="number" step="any" name="discount-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->discount[$val->suffix])echo $this->allItems->discount[$val->suffix];?>" />
								    		<div class="input-group-addon"><?php echo $val->currencySign;?></div>
								    	</div>
								    </span>
							    <?PHP $i++; } ?>
								<?php echo $this->render("languageMutations.phtml"); ?> 
							</div> 
							<div class="col-sm-6">
								<div class="checkbox" style="margin-top: 5px;">
					       			<label> <input type="checkbox" value="1" name="discountInPercentage" <?php if($this->allItems->discountInPercentage)echo "checked";?> class="checkbox">v procentech </label>
					       		</div>
							</div>
						</div>
				    </div>
					<div class="form-group has-feedback">	
					    <label>Text dodání:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
							    <input class="form-control" id="title" type="text" name="deliveryText-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->deliveryText[$val->suffix])echo $this->allItems->deliveryText[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>	
				</div>	
			</div>		
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-block btn-primary  check-product-status-restrictions" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
</form>	
	
