<h1> Upravit produkt </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="">Upravit produkt</li>
	<li class="active"><strong><?php echo $this->allItems->title['cz']?></strong></li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">	
		
			<div class="panel panel-default">
			  <div class="panel-heading">Menu</div>			
			  <ul class="menu list-group">
			  	<?php foreach ($this->subLinks as $val){?>
			    	<li class="list-group-item <?php if($this->sublinkTitle == $val['title']) echo "selected";?> <?php if($this->showOnlyMainSublink && !$val['isMain']) echo "disabled";?>" <?php if($this->showOnlyMainSublink && !$val['isMain']){?> data-toggle="tooltip" data-placement="right" title="Nejprve uložte základní údaje" <?php }?>>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?><a href="<?php echo $val['url'];?>"><?php }?>
			    			<?php echo $val['title'];?>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?></a><?php }?>
			    	</li>
			  	<?php }?>
			  </ul>
			</div>
		</div>	
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">Základní údaje</div>
				
				<div class="panel-body">
					 <div class="form-group has-feedback">	
					 	<label>*Název produktu:</label>	 	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
						    	<input class="form-control <?php if($val->suffix == "cz")echo "required"; ?>" id="title" type="text" name="title-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->title[$val->suffix])echo $this->allItems->title[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				     
				    <div class="form-group has-feedback">		
					 	<label>*Výrobce:</label>	    	    	
					    <select name="supplierID" class="form-control required">
					    	<option value="">-- vyberte výrobce --</option>
					    	<?php foreach ($this->allSuppliers as $val){?>					    		
					    		<option value="<?php echo $val->supplierID?>" <?php if($this->allItems->supplierID == $val->supplierID)echo "selected='selected'"?>><?php echo $val->name?></option>
					    	<?php }?>
					    </select>
				    </div>
				     <div>
						<div class="form-group main-link">
					    <label for="parent">Přiřadit ke kategorii:</label>
						    <span id="selected-parent-link" class="selected-link" rel="0">
						    	<span class="value form-control v-0"><?PHP if(!empty($this->linkID[0]) && $this->linkTitleList[$this->linkID[0]->linkID])echo $this->linkTitleList[$this->linkID[0]->linkID]; else echo "&nbsp;"; ?></span>
							    <span class="parrent-links">
									<?PHP  echo $this->linksOutput ; ?>
							    </span>
						    	<input type="hidden" name="linkID[]" value="<?PHP if(!empty($this->linkID[0]) && $this->linkID[0]->linkID)echo $this->linkID[0]->linkID; else echo 0; ?>" id="selected-parent-input-0" />
						    </span>
						
							<div class="link-List">
							
								<?php if($this->linkCount > 1){ for($i = 1; $i <= $this->linkCount-1; $i++){ ?>
				
									<div class="link-<?php echo $i; ?> has-feedback">
										<label></label>
										<span id="selected-parent-link" class="selected-link" rel="<?php echo $i; ?>">
											<span class="value v-<?php echo $i; ?> form-control"><?PHP if($this->linkTitleList[$this->linkID[$i]->linkID])echo $this->linkTitleList[$this->linkID[$i]->linkID]; else echo "&nbsp;"; ?></span>
										    <span class="parrent-links">
												<?PHP echo $this->linksOutput ; ?>
										    </span>
									    	<input type="hidden" name="linkID[]" value="<?PHP echo $this->linkID[$i]->linkID; ?>" id="selected-parent-input-<?php echo $i; ?>" />
									    </span>
									    <span id="link-<?php echo $i; ?>" class="remove-link"></span>
									</div>
								
								<?php }} ?>							
							</div>
							<span class="btn-xs btn-primary add-link">Přidat kategorii</span>
						</div>
						<input class="link-count" type="hidden" name="link-count" value="<?php if($this->linkCount > 0)echo $this->linkCount;else echo "0"; ?>" />
					</div>
				     
				    
			       	<div class="radio row">
				    	<div class="col-sm-4"><strong>Zobrazit Produkt:</strong></div>
			       		<label class="radio-inline"> <input type="radio" value="1" name="showProduct" class="checkbox" <?PHP if($this->allItems->showProduct || empty($this->allItems->showProduct))echo "checked='checked'"; ?>>Ano </label>
			       		<label class="radio-inline"> <input type="radio" value="0" <?PHP if(empty($this->allItems->showProduct) && is_numeric($this->allItems->showProduct))echo "checked='checked'"; ?> name="showProduct" class="checkbox" >Ne </label>
			       	</div>
			       	<div class="radio row">
				    	<div class="col-sm-4"><strong>Zobrazit facebook:</strong></div>
			       		<label class="radio-inline"> <input type="radio" value="1" name="showFacebook" class="checkbox" <?PHP if($this->allItems->showFacebook || empty($this->allItems->showFacebook))echo "checked='checked'"; ?>>Ano </label>
			       		<label class="radio-inline"> <input type="radio" value="0" <?PHP if(empty($this->allItems->showFacebook) && is_numeric($this->allItems->showFacebook))echo "checked='checked'"; ?> name="showFacebook" class="checkbox" >Ne </label>
			       	</div>
			       	<div class="form-group row">
				    	<div class="col-sm-8"><strong>* Zobrazit v jazycích:</strong></div>
				    	<div class="row">
					    	<div class="col-xs-12 required-checkboxes">
						    	<?php foreach ($this->allLanguageMutations as $val){?>
						    		<div class="col-sm-2">
						    			<label class="checkbox-inline">
						    				<input class="checkbox" type="checkbox" name="showInLanguages[]" <?php if(!empty($this->allDisplayLanguagesArr[$val->languageID])) echo "checked";?> value="<?php echo $val->languageID?>"> 
						    				<?php echo $val->title?>
						    			</label>
						    		</div>
						    	<?php }?>
					    	</div>
				    	</div>
				    </div>
				    <div class="form-group">	
				    	<label>Text:</label>
						<?php echo $this->render("languageMutations.phtml"); ?>  
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    		<textarea id="text-<?PHP echo $val->suffix ?>" class="basic form-control" placeholder="Text" name="text-<?PHP echo $val->suffix ?>"><?php if($this->allItems->text[$val->suffix])echo $this->allItems->text[$val->suffix]; ?></textarea>
					    		<script>execTinyMCE(0,'text-<?PHP echo $val->suffix ?>');</script>
						    </span>
					    <?PHP $i++; } ?>	    	
				    </div>
				    <div class="form-group">	
				    	<label>Dodací lhůta:</label>
						<?php echo $this->render("languageMutations.phtml"); ?>  
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    		<textarea id="deliveryTime-<?PHP echo $val->suffix ?>" class="basic form-control" placeholder="Dodací lhůta" name="deliveryTime-<?PHP echo $val->suffix ?>"><?php if($this->allItems->deliveryTime[$val->suffix])echo $this->allItems->deliveryTime[$val->suffix]; ?></textarea>
					    		<script>execTinyMCE(0,'deliveryTime-<?PHP echo $val->suffix ?>');</script>
						    </span>
					    <?PHP $i++; } ?>	    	
				    </div>  					
					<div class="form-group">
					 	<label>Meta nadpis:</label>	 
						<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
								<input class="form-control" id="metaTitle" type="text" name="metaTitle-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->metaTitle[$val->suffix])echo $this->allItems->metaTitle[$val->suffix];?>" />
							</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
					</div>
					<div class="form-group">
					 	<label>Meta klíčová slova:</label>	
						<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
								<input class="form-control" id="keywords" type="text" name="keywords-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->keywords[$val->suffix])echo $this->allItems->keywords[$val->suffix];?>" />
							</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
					
					</div>
					<div class="form-group">
					 	<label>Meta popis:</label>	 
						<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    			<input class="form-control" id="description" type="text" name="description-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->description[$val->suffix])echo $this->allItems->description[$val->suffix];?>" />
							</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
				    </div>
					<div class="form-group">
					 	<label>Odkaz na produkt v předchozí verzi eshopu:</label>	    
						<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    			<input class="form-control" id="description" type="text" name="oldUrl-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->oldUrl[$val->suffix])echo $this->allItems->oldUrl[$val->suffix];?>" />
							</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
				    </div>
				</div>	
			</div>		
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-block btn-primary check-required-fields check-category-selected" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
</form>	
	
