<script type="text/javascript">
 	$(document).ready(function() {
								
		$( "#date" ).datepicker({
				showOn: "button",
				buttonImage: "/Public/Images/Admin/button.png",
				buttonImageOnly: true
		});
	});
</script>
<h1> Upravit produkt </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="">Upravit produkt</li>
	<li class="active"><strong><?php echo $this->allItems->title['cz']?></strong></li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">	
		
			<div class="panel panel-default">
			  <div class="panel-heading">Menu</div>			
			  <ul class="menu list-group">
			  	<?php foreach ($this->subLinks as $val){?>
			    	<li class="list-group-item <?php if($this->sublinkTitle == $val['title']) echo "selected";?> <?php if($this->showOnlyMainSublink && !$val['isMain']) echo "disabled";?>" <?php if($this->showOnlyMainSublink && !$val['isMain']){?> data-toggle="tooltip" data-placement="right" title="Nejprve uložte základní údaje" <?php }?>>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?><a href="<?php echo $val['url'];?>"><?php }?>
			    			<?php echo $val['title'];?>
			    		<?php if(($this->showOnlyMainSublink && $val['isMain']) || !$this->showOnlyMainSublink){?></a><?php }?>
			    	</li>
			  	<?php }?>
			  </ul>
			</div>
		</div>	
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">Seznam potahů</div>
				
				<div class="panel-body">	
					<div>Označte potahy, které nechcete u produktu zobrazovat.</div>	
						
			
					<div class="clearfix data-list header">
						<div class="col-sm-3 no-left-padding th">Název potahu</div>
						<div class="col-sm-3 th text-center">Zkratka</div>
						<div class="col-sm-6 text-right th">nezobrazovat <input type="checkbox" name="check-all-exclude-covers" value="1" /></div>		
					</div> 
					<ul class="sortListBasic data-list main-ul eshopProduct">   
				       	<?php foreach($this->allCovers as $val){ ?>
						        <li class="clearfix" id="<?php echo $val->coverID ?>">               
									<div class="col-sm-3 first-col text-overflow title" ><?php echo $val->titleSupplier; ?></div>
									<div class="col-sm-3 text-center text-overflow shortcut" ><?php echo $val->coverShortcut; ?></div>
									<div class="col-sm-6 text-right">
									    <input class="delete" type="checkbox" name="coverIDs[]" value="<?php echo $val->coverID ?>" <?php if(!empty($this->allExcludedCovers[$val->coverID]))echo "checked";?>>
									</div>
									
									<br id="endFloat" />
				                
				                </li>
						<?php } ?>
					</ul>
				</div>
			</div>		
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-block btn-primary " type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
</form>	
	
