<h1> Upravit kategorii </h1>

<ol class="breadcrumb">
	<li>Obsah</li>
	<li class="active">Upravit kategorii</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">
     
     <div class="row">	
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading"><span class="glyphicons glyphicons-show-thumbnails-with-lines"></span> Obecný formulář</div>
				<div class="panel-body">   
  		 
			        <div class="form-group has-feedback">
					    
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    		<input placeholder="Název odkazu" class="form-control" id="title" type="text" name="title-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->title[$val->suffix]; ?>" />
						    	<span class="requiere">*</span>
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
					</div>
					
					<div class="radio row"> 		
						<div class="col-sm-4"><strong>Aktivní:</strong></div>
						<div class="col-sm-8 text-left">
							<label class="radio-inline">
								<input class="checkbox" type="radio" name="active" id="active" value="1" <?PHP if($this->allItems->active == 1)echo "checked='checked'" ?>  />
								Ano
							</label>
							<label class="radio-inline">
								<input class="checkbox" type="radio" name="active" id="active" value="0" <?PHP if($this->allItems->active == 0)echo "checked='checked'" ?> />
								Ne
					    	</label>
				    	</div>
				    </div>
				    		
				</div>
			</div>
			
			<div class="well">
				<div class="clearfix">
					<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
						<input class="btn btn-primary btn-block" type="submit" name="enter" value="Upravit" />
					</div>
				</div>
			</div>

		</div>

    </div>  
    	
</form>
