<h1> Emaily uživatelů </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="active">Emaily uživatelů</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">
	<div class="panel panel-default">		
		<div class="panel-heading clearfix">

		</div>
		<div class="panel-body table-responsive">
		
			
			<form action="" method="post">
				<input type="submit" class="btn btn-primary" name="enter" value="Exportovat emaily do CSV" />
			</form>
			
				
		</div>	
		<div class="panel-footer clearfix">
			
			
		</div>	
	</div>
</form>








