<h1> Seznam odkazů </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="active">Seznam odazů</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">
	<div class="panel panel-default">		
		<div class="panel-heading clearfix">
			
				<div class="row">
					<div class="col-sm-6">
						<a class="btn btn-sm btn-success delButton" href="/admin/eshop/kategorie/pridat"> Přidat novou kategorii </a>
					</div>
					<div class="text-right col-sm-6">
						<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
					</div>
				</div>
			
		</div>
		<div class="panel-body table-responsive">
		
			<div class="clearfix data-list header">
				<div class="col-sm-3 no-left-padding th">Název odkazu</div>
				<div class="col-sm-2 text-center th">Zkratka</div>
				<div class="col-sm-3 th">Datum</div>
				<div class="col-sm-2 text-center th">Shlédnuto</div>
				<div class="col-sm-2 text-right th">upravit / smazat</div>		
			</div>
			
			<?PHP echo $this->linksOutput; ?>
			
				
		</div>	
		<div class="panel-footer clearfix">
			
			<div class="text-right">
				<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
				<input type="submit" class ="hidden deleteButton" name="deleteButton" />
			</div>
			
		</div>	
	</div>
</form>








