            <p><label>Soubory: </label><span> (Nově nahrané soubory mají morodré orámování a podklad) </span> </p>
            <script>
            	var fAction       = '<?php echo $this->fAction; ?>';
            	var fFolder       = '<?php echo $this->fFolder; ?>';
            	var fTable        = '<?php echo $this->fTable; ?>';
            	var fTableID      = '<?php echo $this->fTableID; ?>';
            	var fUi           = '<?php echo $this->adminUserID; ?>';
            	var fPath         = '<?php echo $this->fPath; ?>';
            	var fTableIDvalue = '<?php echo $this->fTableIDvalue; ?>';
            </script>
                      
            <script type="text/javascript" src="/Public/Jscripts/AdminBase/addFile.js"></script>
			<script type="text/javascript" src="/Public/Jscripts/Upload/addFileDispatch.js"></script>

		    <div class="other-files">
		        	<div class="galleryPhotos clearfix">
						<?php if($this->allFiles)foreach($this->allFiles as $item){ ?>
							
							<div class="photo">
								<img title="<?php echo $item->title ?>" alt="<?php echo $item->title ?>" src="/Public/Images/Admin/<?php echo $item->ico; ?>?<?php echo rand(0,999); ?>" />
								
								<p>
									<input id="del<?php echo $item->fileID."-e";?>" value="<?php echo $item->fileID."-e";?>" class="checkbox" type="checkbox" name="delete" />							
						    		<a title="Smaž" onclick="checkCheckbox(this);return false;" href="<?php echo $item->fileID."-e";?>"><img alt="Smaž" src="<?php echo $this->baseUrl ?>/Public/Images/Admin/delete.png" /></a>
								</p>
								<p class="file-title"><?php echo $item->title ?></p>
								<p>										
									<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
									   	<span class="language-input <?PHP if($i != 0)echo "hidden "; echo $val->suffix ?>" >
											<input type="text" name="<?php echo $item->fileID."-e";?>-fileDesc-<?PHP echo $val->suffix ?>" value="<?PHP echo $item->description[$val->suffix] ?>" style="width: 200px; margin-right: 5px;" />
										</span>
									<?PHP $i++; } ?>
									<?php echo $this->render("photoLanguageMutations.phtml"); ?>  
								</p>
							</div>
							
						<?php } ?>
						<?php if($this->allTempFiles)foreach($this->allTempFiles as $item){ ?>
							
							<div class="photo photoTemp">
								<img title="<?php echo $item->title ?>" alt="<?php echo $item->title ?>" src="/Public/Images/Admin/<?php echo $item->ico; ?>?<?php echo rand(0,999); ?>" />
								<input type="hidden" name="files[]" value="<?php echo $item->title; ?>~<?php echo $item->fileTempID."-t"; ?>~<?php echo $item->ico; ?>" />
								<p>
									<input id="del<?php echo $item->fileTempID."-t";?>" value="<?php echo $item->fileTempID."-t";?>" class="checkbox" type="checkbox" name="delete" />							
						    		<a title="Smaž" onclick="checkCheckbox(this);return false;" href="<?php echo $item->fileTempID."-t";?>"><img alt="Smaž" src="<?php echo $this->baseUrl ?>/Public/Images/Admin/delete.png" /></a>
								</p>
								<p class="file-title"><?php echo $item->title ?></p>
								<p>										
									<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
									   	<span class="language-input <?PHP if($i != 0)echo "hidden "; echo $val->suffix ?>" >
											<input type="text" name="<?php echo $item->fileTempID."-t";?>-fileDesc-<?PHP echo $val->suffix ?>" value="" style="width: 200px; margin-right: 5px;" />
										</span>
									<?PHP $i++; } ?>
									<?php echo $this->render("photoLanguageMutations.phtml"); ?>  
								</p>
							</div>
							
						<?php } ?>
						<div id="endFloat"></div>
					</div>
					
					<div id="file-fileQueue"></div>
					<input type="file" name="file-uploadify" id="file-uploadify" />
					
					<p class="file-links">
						<?php if(count($this->allFiles) > 0 || count($this->allTempFiles) > 0){ ?>
							  <a href="#" onclick="deleteFiles();return false;"> Smazat označené</a>
						<?php } ?>	
					</p> 
				
		     </div>