<h1 class="font-weight-light mt-4"> Přidat uživatele </h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Uživatelé</li>
        <li class="breadcrumb-item active">Přidat uživatele</li>
    </ol>
</nav>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post" enctype="multipart/form-data">

	<div class="card">		
	
		<div class="card-header d-flex align-items-center">
			Obecný formulář
		</div>
		
		<div class="card-body"> 
			<div class="row"> 
				<div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label class="font-weight-bold d-block">Titul: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="degree" value="<?php if($this->degree)echo $this->degree;?>" />
				    	</div>
				    </div>
			    </div> 
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Jméno: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="name" value="<?php if($this->name)echo $this->name;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Příjmení: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="surname" value="<?php if($this->surname)echo $this->surname;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Společnost: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="spol" value="<?php if($this->spol)echo $this->spol;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Ulice: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="street" value="<?php if($this->street)echo $this->street;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">PSČ: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="zip" value="<?php if($this->zip)echo $this->zip;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Město: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="city" value="<?php if($this->city)echo $this->city;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Tel.: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="tel" value="<?php if($this->tel)echo $this->tel;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Email: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="email" value="<?php if($this->email)echo $this->email;?>" />
				    	</div>
				    </div>
			    </div>
			    <div class="col-sm-6 col-md-4">
			    	<div class="form-group">
				    	<label class="font-weight-bold d-block">Heslo: </label> 
				
				    	
    				    <div class="input-group mb-3">
			    			<input id="password" class="form-control" type="text" name="password" value="<?php if($this->password)echo $this->password;?>" />
                          <div class="input-group-append">
                            <button class="btn btn-outline-secondary" onclick="generatePassword(8);return false;" type="button">Vygeneruj heslo</button>
                          </div>
                        </div>
				    </div>
			    </div>
			     
			    <div class="col-sm-6 col-md-4">
		    		<div class="form-group">
				    	<label class="font-weight-bold d-block">Zasílat emaily:</label>
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="sendEmails" id="sendEmails1" value="1" <?PHP if($this->sendEmails == 1)echo "checked='checked'"; ?> /><label class="form-check-label" for="sendEmails1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="sendEmails" id="sendEmails2" value="0" <?PHP if($this->sendEmails == 0)echo "checked='checked'"; ?> /><label class="form-check-label" for="sendEmails2">Ne</label>
				    	</div>
				    </div>  
		    	</div>
			    
		        <?php if(count($this->allCategories) > 0){ ?>
		        
		        	 <p>
				         <label class="font-weight-bold d-block"><?PHP echo $this->translate("Přidat do kategorie"); ?>:</label>		        	
				         <input id="all-cat-user" type="checkbox" <?php if(!$this->categories || count($this->categories) == count($this->allCategories)){echo" checked ";} ?> class="checkbox" name="all-cat" value="1" /> <label for="select-all-cat"><?PHP echo $this->translate("Všechny kategorie"); ?></label>
				     </p>    
			     
					 <ul class="equipment">
					    <?php foreach($this->allCategories as $cat){ ?>			        	
				        	    <?php 
				        	    	$checked = false;
				        	    	if($this->categories){
					        	    	foreach($this->categories as $c){ 
					        	    		if($c == $cat->categoryID){
					        	    			$checked = true;
					        	    			break;
					        	    		}
					        	    	}
				        	    	}
				        	    	
				        	    ?>	        	      	
					      <li>
					       	<input <?php if(!$this->categories || $checked)echo" checked ";?> id="cat-<?PHP echo $cat->categoryID ?>" type="checkbox" class="checkbox user-cat-check" name="categories[]" value="<?php echo $cat->categoryID ?>" />
					       	<label for="cat-<?PHP echo $cat->categoryID ?>"><?php echo $cat->title; ?></label>
					      </li>
					     <?php } ?>
					 </ul>
					 <br class="clear-left" />
		        
		        <?php } ?>

	        </div>
		</div>
	</div>
	
	<div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block" type="submit" name="enter" value="Přidat" />
			</div>
		</div>
	</div>
	
</form>

	
    