<h1> Seznam uživatelů </h1>

<ol class="breadcrumb">
<li>Uživatelé</li>
<li class="active">Seznam uživatelů</li>
</ol>

<div class="panel panel-default">		
	<div class="panel-heading clearfix">
		<div class="row">
			<div class="col-xs-9">
	    		<?php if(!$this->sortableList)echo $this->render('userAlign.phtml');else echo $this->render('sortAlign.phtml'); ?>
			</div>
			<div class="col-xs-3 text-right">
				<div class="form-group">
					<a class="btn btn-sm btn-success" href="/admin/uzivatele/uzivatel/pridat"> Přidat </a>
				</div>
				<div class="form-group">
					<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
				</div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="panel-body table-responsive">
	
		<div class="clearfix data-list header">
				<div class="col-sm-2 no-left-padding th">Jméno a příjmení</div>
				<div class="col-sm-2 text-center th">Datum zal.</div>
				<div class="col-sm-4 text-center th">Email</div>
				<div class="col-sm-2 text-center th">Tel</div>
				<div class="col-sm-2 no-padding-right text-right th">upravit / smazat</div>		
		</div>
				
		<ul class="data-list main-ul">        
	    <?php foreach($this->allItems as $item){ ?>
			<li>
	            <div class="col-sm-2 no-left-padding"> <?php echo $item->degree." ".$item->name." ".$item->surname; ?></div>
	            <div class="col-sm-2 text-center"> <?php echo $item->date; ?></div>
				<div class="col-sm-4 text-center"> <?php echo $item->email; ?></div>
				<div class="col-sm-2 text-center"> <?php echo $item->tel; ?></div>
				<div class="col-sm-2 no-padding-right text-right">
				    <a title="Uprav" href="<?php echo $this->baseUrl; ?>/admin/uzivatele/uzivatel/upravit/id/<?php echo $item->userID;?>"><span class="glyphicons glyphicons-pencil"></span></a>   
				    <input class="delete" type="checkbox" name="delete[]" value="<?php echo $item->userID ?>">
				</div>
				
				<br id="endFloat" />
           </li>
	    <?php } ?>
    	</ul>
    </div>
		
<?php echo $this->nextPrevious ?>
</div>

 
