<h1> Upravit uživatele </h1>

<ol class="breadcrumb">
<li>Uživatelé</li>
<li class="active">Upravit uživatele</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post" enctype="multipart/form-data">

	<div class="panel panel-default">		
		
		<div class="panel-heading">
			Obecný formulář
		</div>
		
		<div class="panel-body">
	    	<div class="row">
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label>Titul: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="degree" value="<?php echo $this->allItems->degree; ?>" />
				    	</div>
				    </div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
					    <label for="name">Jméno: </label>
						<div>
							<input class="form-control" type="text" name="name" value="<?php echo $this->allItems->name; ?>" />
						</div>
					</div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="name">Příjmení: </label>
						<div>
							<input class="form-control" type="text" name="surname" value="<?php echo $this->allItems->surname; ?>" />
						</div>
					</div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="name">Společnost: </label> 
				    	<div>
							<input class="form-control" type="text" name="spol" value="<?php echo $this->allItems->spol; ?>" />
						</div>
					</div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
					    <label for="name">Ulice: </label> 
					    <div>
					    	<input class="form-control" type="text" name="street" value="<?php echo $this->allItems->street; ?>" />
					    </div>
				    </div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="name">PSČ: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="zip" value="<?php echo $this->allItems->zip; ?>" />
				    	</div>
				    </div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
					    <label for="name">Město: </label>
					    <div>
					    	<input class="form-control" type="text" name="city" value="<?php echo $this->allItems->city; ?>" />
					    </div>
				    </div>
				</div>
			    <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="name">Tel.: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="tel" value="<?php echo $this->allItems->tel; ?>" />
				    	</div>
			    	</div>
			    </div>
			    
		        <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="email">Přihlašovací E-mail: </label> 
				    	<div>
				    		<input class="form-control" type="text" name="email" value="<?php echo $this->allItems->email; ?>" />
				    	</div>
					</div>
				</div>
		        <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
			    		<label for="title">Zablokován přístup: </label>	
			    		<div>    
						   <label class="radio-inline"><input type="radio" value="1" name="blocked" class="checkbox" <?PHP if($this->allItems->blocked == 1)echo"checked" ?> >Ano </label>
						   <label class="radio-inline"><input type="radio" value="0" name="blocked" class="checkbox" <?PHP if($this->allItems->blocked == 0)echo"checked" ?> >Ne </label>
					    </div>	
				    </div>
				</div>
				
				<div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
			    		<label for="title">Zasílat emaily: </label>
			    		<div>
					    	<label class="radio-inline"><input type="radio" value="1" name="sendEmails" class="checkbox" <?PHP if($this->allItems->sendEmails == 1)echo"checked" ?> >Ano</label>
				    		<label class="radio-inline"><input type="radio" value="0" name="sendEmails" class="checkbox" <?PHP if($this->allItems->sendEmails == 0)echo"checked" ?> >Ne</label>
		    			</div>   
		    		</div> 
		    	</div>
		    </div>
		    <div class="row">
		         
		        <div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="password">Vytvořit nové heslo: </label> 
				    	<div class="input-group">
				    		<input class="form-control" id="password" type="text" name="password" value="" /> 
				    		<div class="input-group-addon"><a onclick="generatePassword(8);return false;" class="button" href="">Vygeneruj heslo</a></div>
						</div>
					</div>
				</div>
		     	<div class="col-sm-6 col-md-4"> 
				    <div class="form-group">
				    	<label for="passwordConfirm">Nové heslo znovu: </label> 
				    	<div>
				    		<input class="form-control" id="passwordConfirm" type="text" name="passwordConfirm" value="" />
				    	</div>
				    </div>
				</div>
		     	
		     	<?php if(count($this->allCategories) > 0){ ?>
		     	
				     <p>
					     <label><?PHP echo $this->translate("Přidat do kategorie"); ?>:</label>		        	
				     </p> 
					 <ul class="equipment">
					    <?php foreach($this->allCategories as $cat){ ?>			        	
					        	    <?php 
					        	    	$checked = false;
					        	    	if($this->allUsersCategories){
						        	    	foreach($this->allUsersCategories as $c){ 
						        	    		if($c->categoryID == $cat->categoryID){
						        	    			$checked = true;
						        	    			break;
						        	    		}
						        	    	}
					        	    	}
					        	    	
					        	    ?>	        	      	
						      <li>
						       	<input <?php if($checked)echo" checked ";?> id="cat-<?PHP echo $cat->categoryID ?>" type="checkbox" class="checkbox user-cat-check" name="categories[]" value="<?php echo $cat->categoryID ?>" />
						       	<label for="cat-<?PHP echo $cat->categoryID ?>"><?php echo $cat->title; ?></label>
						      </li>
					     <?php } ?>
					 </ul>
					 <br class="clear-left" />
				 
				 <?php } ?>
		     	
	        </div>
		</div>
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-primary btn-block" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>

</form>
