<script type="text/javascript" src="/Application/Modules/Seo/Sitemap/Jscripts/events.js"></script>

<h1> Robots </h1>

<ol class="breadcrumb">
<li>SEO</li>
<li class="active">Robots</li>
</ol>

<?php if($this->error !=''){
	echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";
} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">

	<div class="panel panel-default">		
		<div class="panel-heading clearfix">

		</div>
		<div class="panel-body">

			<label>Text souboru robots.txt</label>
			<div class="form-group">
				<textarea class="form-control" name="robots"><?php echo $this->allData->robots; ?></textarea>
			</div>
			
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-primary btn-block" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>

</form>
