<script type="text/javascript" src="/Application/Modules/Seo/Sitemap/Jscripts/events.js"></script>

<h1 class="font-weight-light mt-4"> Robots </h1>
<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">SEO</li>
        <li class="breadcrumb-item active">Robots</li>
    </ol>
</nav>
<?php if($this->error !=''){
	echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";
} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">

	<div class="card">		
		<div class="card-header d-flex align-items-center">
		robots.txt
		</div>
		<div class="card-body">

			<label>Text souboru robots.txt</label>
			<div class="form-group">
				<textarea rows="5" class="form-control" name="robots"><?php echo $this->allData->robots; ?></textarea>
			</div>
			
		</div>	
	</div>
	<div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block check-required-fields" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
</form>
