<?php echo $this->render("css-js.phtml"); ?>

<h1> Seznam článků </h1>

<ol class="breadcrumb">
<li>Obsah</li>
<li class="active">Seznam článků</li>
</ol>

<?php if($this->error !=''){
	echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";
} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">

<div class="panel panel-default">		
		<div class="panel-heading clearfix">
			<div class="float-left">
				<?php echo $this->render('sortAlignClanky.phtml'); ?>
			</div>
			<div class="float-right text-right">
				<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
			</div>
			
		</div>
		<div class="panel-body table-responsive">

			<div class="clearfix data-list header">
				<div class="col-sm-2 no-left-padding th">Hlavní odkaz</div>
				<div class="col-sm-2 th">Přiřazano k odkazu</div>
				<div class="col-sm-4 th">Název článku</div>
				<div class="col-sm-2 text-center th">Shlédnuto</div>
				<div class="col-sm-2 text-right th">upravit / smazat</div>		
			</div>

			<?php if(count($this->allItems) > 0){ ?>	
		    <ul class="sortListBasic data-list main-ul article">
				<?php foreach($this->allItems as $actuality){ ?>
				        <li class="clearfix" id="<?php echo $actuality->articleID ?>">               
			                <div class="col-sm-2 first-col text-overflow" title="<?php echo $actuality->topLinkTitle; ?>" ><span class="glyphicons glyphicons-move"></span> <?php echo $actuality->topLinkTitle; ?></div>
							<div class="col-sm-2 text-overflow" title="<?php echo $actuality->lastLinkTitle; ?>" ><?php echo $actuality->lastLinkTitle; ?></div>
							<div class="col-sm-4 text-overflow" ><?php echo $actuality->title; ?></div>
							<div class="col-sm-2 text-center" ><?php echo $actuality->view; ?></div>
							<div class="col-sm-2 text-right">
							    <a title="<?PHP echo $this->translate('Uprav'); ?>" href="<?php echo $this->baseUrl; ?>/admin/obsah/clanky/upravit/id/<?php echo $actuality->articleID?>"><span class="glyphicons glyphicons-pencil"></span></a>   
							    <?PHP if($actuality->allowDelete){ ?>
							    	<input class="delete" type="checkbox" name="delete[]" value="<?php echo $actuality->articleID ?>">
								<?PHP } ?>
							</div>
							
							<br id="endFloat" />
		                
		                </li>
				<?php } ?>
			</ul>
			<?php }else{ ?>
				<div class="no-data alert alert-warning text-center">Zatím se zde nenachází žádné články.</div>
			<?php } ?>

		</div>	
		<div class="panel-footer clearfix">
			
				<div class="text-right">
					<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
					<input type="submit" class ="hidden deleteButton" name="deleteButton" />
				</div>
			
		</div>	
	</div>

</form>

