<?php echo $this->render("css-js.phtml"); ?>

<h1 class="font-weight-light mt-4"> Seznam článků </h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Obsah</li>
        <li class="breadcrumb-item active">Seznam článků</li>
    </ol>
</nav>


<?php if($this->error !=''){
	echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";
} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">

<div class="card">		
		<div class="card-header d-flex align-items-center">
			<?php echo $this->render('sortAlignClanky.phtml'); ?>
			<button type="button" class="btn btn-sm btn-danger delButton text-uppercase ml-auto"> Smazat označené </button>			
		</div>
		<div class="card-body">
			<?php if(count($this->allItems) > 0){ ?>
    			<table class="table table-striped">
                  <thead>
                    <tr>
                      <th scope="col" class="text-left">Hlavní odkaz</th>
                      <th scope="col" class="text-center">Přiřazano k odkazu</th>
                      <th scope="col" class="text-center">Název článku</th>
                      <th scope="col" class="text-center">Shlédnuto</th>
                      <th scope="col" class="text-right">upravit / smazat</th>
                    </tr>
                  </thead>
                  <tbody class="sortListBasic data-list main-ul article ui-sortable">
                  
    				<?php foreach($this->allItems as $actuality){ ?>    		                
    		                <tr id="<?php echo $actuality->articleID ?>">
                              <td class="text-left align-middle"><span class="glyphicons glyphicons-move"></span> <?php echo $actuality->topLinkTitle; ?></td>
                              <td class="text-center align-middle"><?php echo $actuality->lastLinkTitle; ?></td>
                              <td class="text-center align-middle"><?php echo $actuality->title; ?></td>
                              <td class="text-center align-middle"><?php echo $actuality->view; ?></td>
                              <td class="text-right align-middle">
                          		<a class="d-inline-block align-middle" title="<?PHP echo $this->translate('Uprav'); ?>" href="<?php echo $this->baseUrl; ?>/admin/obsah/clanky/upravit/id/<?php echo $actuality->articleID?>"><span class="glyphicons glyphicons-pencil"></span></a>   
							    <?PHP if($actuality->allowDelete){ ?>
							    	<input class="d-inline-block delete align-middle ml-2" type="checkbox" name="delete[]" value="<?php echo $actuality->articleID ?>">
								<?PHP } ?>
    						  </td>
                            </tr>
    				<?php } ?>
                    
                  </tbody>
                </table>
			

			<?php }else{ ?>
				<div class="no-data alert alert-warning text-center">Zatím se zde nenachází žádné články.</div>
			<?php } ?>

		</div>	
		<div class="card-footer">
			
				<div class="text-right">
					<button type="button" class="btn btn-sm btn-danger delButton text-uppercase"> Smazat označené </button>
					<input type="submit" class ="d-none deleteButton" name="deleteButton" />
				</div>
			
		</div>	
	</div>

</form>

