<script type="text/javascript">
 	$(document).ready(function() {
								
		$( "#date" ).datepicker({
				showOn: "button",
				buttonImage: "/Public/Images/Admin/button.png",
				buttonImageOnly: true
		});
	});
</script>
<h1 class="font-weight-light mt-4"> Upravit článek </h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Obsah</li>
        <li class="breadcrumb-item active">Upravit článek</li>
    </ol>
</nav>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md">
			
            <div class="card mb-4">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-show-thumbnails-with-lines pr-3 color-black"></span><span class="text">Obecný formulář</span>
        		</div>
        		<div class="card-body">
					<div class="form-group">
				       	<label class="font-weight-bold d-block">Zobrazit článek:</label>
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="showArticle" id="showArticles1" value="1" <?PHP if($this->allItems->active || empty($this->allItems->active))echo "checked='checked'"; ?> /><label class="form-check-label" for="showArticles1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="showArticle" id="showArticles2" value="0" <?PHP if(empty($this->allItems->active) && is_numeric($this->allItems->active))echo "checked='checked'"; ?> /><label class="form-check-label" for="showArticles2">Ne</label>
				    	</div>
			       	</div>
				
				    <div class="form-group has-feedback">
				    	<label class="font-weight-bold d-block">Název článku</label>
				        <div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
							    	<input class="form-control" placeholder="Název článku" id="title" type="text" name="title-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->title[$val->suffix])echo $this->allItems->title[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
			        </div>						 
				    <div>
						<div class="form-group main-link">
					    	<label for="parent">Přiřadit k odkazu:</label>
						    <span id="selected-parent-link" class="selected-link" rel="0">
						    	<span class="value form-control v-0"><?PHP if(!empty($this->linkID[0]) && $this->linkTitleList[$this->linkID[0]->linkID])echo $this->linkTitleList[$this->linkID[0]->linkID]; else echo "&nbsp;"; ?></span>
							    <span class="parrent-links">
									<?PHP  echo $this->linksOutput ; ?>
							    </span>
						    	<input type="hidden" name="linkID[]" value="<?PHP if(!empty($this->linkID[0]) && $this->linkID[0]->linkID)echo $this->linkID[0]->linkID; else echo 0; ?>" id="selected-parent-input-0" />
						    </span>
						
							<div class="link-List mb-1">
							
								<?php if($this->linkCount > 1){ for($i = 1; $i <= $this->linkCount-1; $i++){ ?>
				
									<div class="link-<?php echo $i; ?>">
										<label></label>
										<span id="selected-parent-link" class="selected-link" rel="<?php echo $i; ?>">
											<span class="value v-<?php echo $i; ?> form-control"><?PHP if($this->linkTitleList[$this->linkID[$i]->linkID])echo $this->linkTitleList[$this->linkID[$i]->linkID]; else echo "&nbsp;"; ?></span>
										    <span class="parrent-links">
												<?PHP echo $this->linksOutput ; ?>
										    </span>
									    	<input type="hidden" name="linkID[]" value="<?PHP echo $this->linkID[$i]->linkID; ?>" id="selected-parent-input-<?php echo $i; ?>" />
									    </span>
									    <span id="link-<?php echo $i; ?>" class="remove-link"></span>
									</div>
								
								<?php }} ?>							
							</div>
							<span class="btn btn-xs btn-primary add-link">Přidat odkaz</span>
						</div>
						<input class="link-count" type="hidden" name="link-count" value="<?php if($this->linkCount > 0)echo $this->linkCount;else echo "0"; ?>" />
					</div>
				    
				    <div class="form-group">
				    	<label class="font-weight-bold d-block">Datum vložení</label>
				    	<div class="position-relative">
				    		<input id="date" class="form-control pr-5" type="text" name="date" value="<?php if($this->allItems->date)echo $this->allItems->date;?>" class="date" />
				    	</div>
				    </div>
				    
					<?PHP if($this->modulesData->clankyDoporucene){ ?>
					    <div class="form-group">
				    		<label class="font-weight-bold d-block">Doporučený</label>
				    		<div>
    				    		<div class="form-check form-check-inline">
        				    		<input id="recommended1" type="radio" value="1" name="recommended" class="form-check-input" <?PHP if($this->allItems->recommended == 1)echo "checked='checked'"; ?>><label class="form-check-label" for="recommended1">Ano</label>
        				    	</div>
    				    		<div class="form-check form-check-inline">
        				    		<input id="recommended2" type="radio" value="0" name="recommended" class="form-check-input" <?PHP if(empty($this->allItems->recommended) || $this->allItems->recommended == 0 )echo "checked='checked'"; ?>><label class="form-check-label" for="recommended2">Ne</label>
        				    	</div>
				    		</div>
				    	</div>
					<?PHP } ?>
					<?PHP if($this->modulesData->clankyFacebook){ ?>
				    	<div class="form-group">
				    		<label class="font-weight-bold d-block">Zobrazit facebook</label>				    		
				    		<div class="form-check form-check-inline">
    				    		<input id="showFacebook1" type="radio" value="1" name="showFacebook" class="form-check-input" <?PHP if($this->allItems->showFacebook == 1)echo "checked='checked'"; ?>><label class="form-check-label" for="recommended1"><?PHP echo $this->translate("Ano"); ?></label>
    				    	</div>
				    		<div class="form-check form-check-inline">
    				    		<input id="showFacebook2" type="radio" value="0" name="showFacebook" class="form-check-input" <?PHP if(empty($this->allItems->showFacebook) || $this->allItems->showFacebook == 0 )echo "checked='checked'"; ?>><label class="form-check-label" for="recommended2"><?PHP echo $this->translate("Ne"); ?></label>
    				    	</div>
				    	</div>
					<?PHP } ?>
					
					<div class="form-group">
				    	<label class="font-weight-bold d-block">Anotace</label>
						<div>
							<?php echo $this->render("languageMutations.phtml"); ?>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<textarea id="a-<?PHP echo $val->suffix ?>" class="basic form-control" placeholder="Anotace"  name="anotation-<?PHP echo $val->suffix ?>">   <?php if($this->allItems->anotation[$val->suffix])echo   $this->allItems->anotation[$val->suffix];?> </textarea>
							    	<script>execTinyMCE(0,'a-<?PHP echo $val->suffix ?>');</script>
							    </span>
						    <?PHP $i++; } ?> 
					    </div>
					</div>
					    					    
					<div class="form-group">
					    <label class="font-weight-bold d-block">Text</label>
						<div>
							<?php echo $this->render("languageMutations.phtml"); ?>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<textarea id="t-<?PHP echo $val->suffix ?>" class="basic form-control" placeholder="Text"  name="text-<?PHP echo $val->suffix ?>">   <?php if($this->allItems->text[$val->suffix])echo   $this->allItems->text[$val->suffix];?> </textarea>
							    	<script>execTinyMCE(0,'t-<?PHP echo $val->suffix ?>');</script>
							    </span>
						    <?PHP $i++; } ?> 
					    </div>
					</div>	
					    
	        	</div>
	        </div>
	        
			<div class="card">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-show-thumbnails-with-lines pr-3 color-black"></span><span class="text">SEO</span>
        		</div>
        		<div class="card-body">
				
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta nadpis</label>
						<div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<input class="form-control" placeholder="Meta nadpis"  id="metaTitle" type="text" name="metaTitle-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->metaTitle[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div>
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta klíčová slova</label>
						<div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<input class="form-control" placeholder="Meta klíčová slova" id="keywords" type="text" name="keywords-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->keywords[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div>
				    <div class="form-group">
					    <label class="font-weight-bold d-block">Meta popis</label>
					    <div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    			<input class="form-control" placeholder="Meta popis" id="description" type="text" name="description-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->description[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
				    </div>
				
				</div>
			</div>     
	        
		</div>
		<div class="col-md">
			<?PHP if($this->modulesData->clankySouvisejici){ ?>
				<div class="card mb-4">		
            		<div class="card-header d-flex align-items-center">
            			<span class="glyphicons glyphicons-bring-to-front pr-3 color-black"></span><span class="text">Související články</span>
            		</div>
            		<div class="card-body">	
			    		<div class="related-articles position-relative">
			    			<label for="description">Seznam souvisejících: </label>	
				            <div>				            					            
					            <span class="selected-articles">
				    				<?PHP if(!empty($this->allRelated)){ ?>
					    				<?PHP $i = 0; foreach ($this->allRelated as $val){ 
					    					if($i % 2 == 0)	$cls = "odd";
					    					else 			$cls = "even";
					    					?>
					    					
					    					<span class="item <?PHP echo $cls ?>">
				 								<span class="title"><?PHP echo $val->title ?></span>
						    					<a href="" class="remove-from-related"></a>
						    					<input class="related-input" type="hidden" value="<?PHP echo $val->articleID ?>" name="related[]" />
						    					<span class="clear-both"></span>					
						    				</span>
					    				
					    				<?PHP $i++; } ?>
					    				
					    				<script type="text/javascript">
						    				//odstrani zaznam ze souvisejicich prispevku(produktu)
										 	$('a.remove-from-related').click(function(){
										 		$(this).parent().remove();
										 		return false;
										 	});
										</script>
				    				<?PHP } ?>
				    			</span>
				            </div>
				            <div class="form-group">
				            	<input class="form-control" placeholder="Přidat související" id="search-input" type="text" name="" value="" />
				            </div>
			    			<div class="search-content-list">                   
				                <ul class="search-content search-content-no-list">
				                    <?PHP foreach ($this->allArticles as $value){ ?>
				                        <li class="related-item" ><?PHP echo $value->title?> <span class="id"><?PHP echo $value->articleID ?></span><span class="title"><?PHP echo $value->title ?></span></li>                        
				                    <?PHP }?>
				                </ul>			             
				            </div>
			    		</div>
					
					</div>
				</div>
			<?php } ?>
			
			<?PHP if($this->modulesData->clankyUrlVideo){ ?>
				<div class="card mb-4">		
                	<div class="card-header d-flex align-items-center">
                		<span class="social social-vimeo pr-3"></span><span class="text">Přidat video (youtube, vimeo)</span>
                	</div>
            		<div class="card-body">	
						<div class="video-URLs">
							<div class="row">
    							<?php $i = 1; foreach($this->allWebVideos as $vid){ ?>	
        								<div class="col-sm-6 col-xs-12">	
            						 		<?PHP if($vid->type == "youtube"){ ?>		    		    	
            									<div class="video-panel">
            										<div class="form-group">
            											<iframe width="230" height="165" src="http://www.youtube.com/embed/<?PHP echo $vid->code ?>" frameborder="0" allowfullscreen></iframe> 
            										</div>
            										<div class="form-group px-2">
            											<div class="form-check form-check-inline">
                                                          <input id="del-vid-<?PHP echo $i ?>" type="checkbox" class="form-check-input" name="delVideo[]" value="<?PHP echo $vid->webVideoID ?>">
                                                          <label class="form-check-label" for="del-vid-<?PHP echo $i ?>">
                                                            smazat video
                                                          </label>
                                                        </div>
            										</div>
            									</div>
            								<?PHP }else if($vid->type == "vimeo"){ ?>
            									<div class="video-panel">
            										<div class="form-group">
            											<iframe src="http://player.vimeo.com/video/<?PHP echo $vid->code ?>?title=0&amp;byline=0&amp;portrait=0" width="230" height="165" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            										</div>
            										<div class="form-group px-2">
            											<div class="form-check form-check-inline">
                                                          <input id="del-vid-<?PHP echo $i ?>" type="checkbox" class="form-check-input" name="delVideo[]" value="<?PHP echo $vid->webVideoID ?>">
                                                          <label class="form-check-label" for="del-vid-<?PHP echo $i ?>">
                                                            smazat video
                                                          </label>
                                                        </div>
            										</div>
            									</div>
            								<?PHP } ?>
            							</div>
    							 <?php $i++; } ?>
							</div>
						</div>
				    	
				    	
					</div>
					<div class="card-footer">
						<a href="" class="btn btn-primary btn-xs add-videoURL text-uppercase">Přidat URL</a>
				    	<input type="hidden" name="hidvideo" value="1">
					</div>
				</div>
							
			<?php } ?>
			
			<?PHP if($this->modulesData->clankyFoto){ ?>
				<div class="card mb-4">		
                	<div class="card-header d-flex align-items-center">
                		<span class="glyphicons glyphicons-picture pr-3"></span><span class="text">Upravit fotky</span>
                	</div>
            		<div class="card-body">
					    <input type="hidden" name="sWidth"  value="256" />
				        <input type="hidden" name="sHeight" value="0" />
				        <input type="hidden" name="mWidth"  value="0" />
				        <input type="hidden" name="mHeight"  value="600" />
				        
				        <script>
			            	var mAction       = '<?php echo $this->action; ?>';
			            	var mFolder       = '<?php echo $this->folder; ?>';
			            	var mTable        = '<?php echo $this->table; ?>';
			            	var mTableID      = '<?php echo $this->tableID; ?>';
			            	var mUi           = '<?php echo $this->adminUserID; ?>';
			            	var mPath         = '<?php echo $this->path; ?>';
			            	var mTableIDvalue = '<?php echo $this->tableIDvalue; ?>';
			            	var sWidth        = $("input[name=sWidth]").val();
			            	var sHeight       = $("input[name=sHeight]").val();
			            	var mWidth        = $("input[name=mWidth]").val();
			            	var mHeight       = $("input[name=mHeight]").val();
			            	var mResizedByLongerSide = "false";
				        </script>
					    <?php echo $this->render("photo.phtml"); ?>
					    
					    <input id="photos-upload" name="photo-files[]" type="file" multiple class="file" data-preview-file-type="text">

						<script>
						
							$("#photos-upload").fileinput({
								'uploadAsync' :true,
								language: "cs",
								uploadUrl: '/core/helper/photo-uploadify/swidth/'+sWidth+'/sheight/'+sHeight+'/mwidth/'+mWidth+'/mheight/'+mHeight+'/resized/'+mResizedByLongerSide+'/tableType/'+mTable+'/user/'+mUi+'/folder/Temp',
								overwriteInitial: false

							}).on('filebatchuploadcomplete', function(event, files, extra) {
							    
							    $.ajax({
								   type: "POST",
								   url: "/core/helper/get-add-photos",
								   data: "folder="+mFolder+"&ui="+mUi+"&table="+mTable+"&tableID="+mTableID+"&tableIDvalue="+mTableIDvalue,
								   success: function(html){    
								       $("div.files").html(html); 
								       $('#photos-upload').fileinput('clear');  
								       setLangs();
								       sortListPhotos();            
						           }
							   });  
							    
							});
						</script>
					    
					    
					    
					</div>
				</div>
			<?php } ?>
			
			<?PHP if($this->modulesData->clankySoubor){ ?>	 	   
				<div class="card mb-4">		
                	<div class="card-header d-flex align-items-center">
                		<span class="glyphicons glyphicons-file pr-3"></span><span class="text">Upravit soubory</span>
                	</div>
            		<div class="card-body">	
		        		<?php echo $this->render("files.phtml"); ?> 
		        	</div>
		        </div>
			<?PHP } ?>
			
			<?PHP if($this->modulesData->clankyMp4Video){ ?>
		        <div class="card mb-4">		
                	<div class="card-header d-flex align-items-center">
                		<span class="glyphicons glyphicons-film pr-3"></span><span class="text">Přidat mp4 videa</span>
                	</div>
            		<div class="card-body">
		        		<?php echo $this->render("video.phtml"); ?> 
		        	</div>
		        </div>		          
			<?PHP } ?>
		</div>
	</div>
	<div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block" type="submit" name="enter" value="Uložit" />
			</div>
		</div>
	</div>
	
</form>
	
	
