<form method="post" name="sendData" class="padding-bottom-20" novalidate>
	<div class="form-group has-feedback">
		<input type="text" class="form-control" name="login" placeholder="Uživatelské jméno" required />		
		<span class="glyphicons glyphicons-user form-control-feedback" aria-hidden="true"></span>		
	</div>
	<div class="form-group has-feedback">
		<input type="password" class="form-control" name="password" placeholder="Heslo" required  />
		<span class="glyphicons glyphicons-lock form-control-feedback" aria-hidden="true"></span>
	</div>
	
	<div class="form-group">
		<button class="btn btn-primary btn-block" type="submit" >Přihlásit se</button>
	</div>
	<div class="form-group">
		<?php if($this->message){ ?><div class="error loginError"><?php echo $this->message ?></div><?php } ?>
	</div>
</form>




