<form method="post" name="sendData" class="pb-4" novalidate>
	<div class="input-group icon mb-3">		
		<div class="input-group-prepend">
        	<span class="glyphicons glyphicons-user input-group-text input-group-icon px-3"></span>
        </div>
		<input type="text" class="form-control" name="login" placeholder="Uživatelské jméno" required />		
	</div>
	<div class="input-group icon mb-3">		
		<div class="input-group-prepend">
        	<span class="glyphicons glyphicons-lock input-group-text input-group-icon px-3"></span>
        </div>
		<input type="password" class="form-control" name="password" placeholder="Heslo" required/>		
	</div>
	<button class="btn btn-primary btn-block mb-3 text-uppercase" type="submit" >Přihlásit se</button>	
	<?php if($this->message){ ?><div class="error loginError"><?php echo $this->message ?></div><?php } ?>	
</form>




