        <div class="list-order form-inline"> 	
            <form action="" method="post">	 
            	<div class="message sortMessage"> </div>
				<a class="btn btn-sm btn-success delButton" href="/admin/obsah/clanky/pridat"> Přidat nový článek </a>
				<select class="form-control" name="subLinkID">
				
					<?php foreach($this->allSublinks as $sublink){ ?>
				    <option <?php if($sublink->linkID == $this->subLinkID) echo "selected"; ?> value="<?PHP echo $sublink->linkID; ?>"><?PHP echo $sublink->title; ?></option>
					<?php } ?>
					<option <?php if($this->subLinkID == 0) echo "selected"; ?> value="0"> -- nezařazené -- </option>
				</select>
				
				<span class="others-link">
				
				
				
				</span>
				
				<input class="button btn btn-sm btn-primary" type="submit" name="vybrat" value="<?PHP echo $this->translate('Vybrat kategiorii'); ?>" />

			</form>
		</div>
		
		<script>getOtherLinks(<?php echo $this->subLinkID; ?>,<?php echo $this->subLinkID1; ?>)</script>
		