<li>
<div class="panel panel-default">
<div class="panel-heading clearfix">
	<span class="label label-success">Link element</span>
	<span class="glyphicons glyphicons-remove link-element" data="<?php echo $this->elementData["linkElement"]["sectionID"]; ?>-<?php echo $this->elementData["linkElement"]["groupLinkID"]; ?>"></span>
	<span class="glyphicons glyphicons-move"></span>
	<span class="element-width form-inline">
		<label>Šířka elementu:</label>
		<select class="form-control" name="l-e-element-width-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>">
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 12) echo "selected = 'selected'"?> value="12">12 dílů (celá šířka)</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 11) echo "selected = 'selected'"?>  value="11">11 dílů</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 10) echo "selected = 'selected'"?>  value="10">10 dílů</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 9) echo "selected = 'selected'"?>  value="9">9 dílů</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 8) echo "selected = 'selected'"?>  value="8">8 dílů</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 7) echo "selected = 'selected'"?>  value="7">7 dílů</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 6) echo "selected = 'selected'"?>  value="6">6 dílů (polovina šířky)</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 5) echo "selected = 'selected'"?>  value="5">5 dílů</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 4) echo "selected = 'selected'"?>  value="4">4 díly</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 3) echo "selected = 'selected'"?>  value="3">3 díly</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 2) echo "selected = 'selected'"?>  value="2">2 díly</option>
			<option <?php if($this->elementData["linkElement"]['elementWidth'] == 1) echo "selected = 'selected'"?>  value="1">1 díl</option>
		</select>
	</span>
</div>
	<div class="panel-body">
	
		<div class="form-group">		
			<label class="label-concrete">Počet sloupců v řádku</label>			
			<select class="form-control" name="l-e-colCount-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>">
				<option <?php if($this->elementData["linkElement"]["colCount"] == 1)echo "selected"; ?> value="1">1</option>
				<option <?php if($this->elementData["linkElement"]["colCount"] == 2)echo "selected"; ?> value="2">2</option>
				<option <?php if($this->elementData["linkElement"]["colCount"] == 3)echo "selected"; ?> value="3">3</option>
				<option <?php if($this->elementData["linkElement"]["colCount"] == 4)echo "selected"; ?> value="4">4</option>
				<option <?php if($this->elementData["linkElement"]["colCount"] == 6)echo "selected"; ?> value="6">6</option>
			</select>
		
		</div>
		<hr />
    	<?php $checkbox = 1; foreach($this->elementData["linkElement"]["data"] as $linkElm){ ?>
	    	<div class="col-sm-4 link-element-item">
				<div class="fileinput fileinput-new" data-provides="fileinput">
					<div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 122px; height: 82px;float:left;margin-right:5px;">
						<?php if(!empty($linkElm["image"])){ ?>
			    			<img src="/Public/Images/Link/Section/Link/mala-<?php echo $linkElm["image"] ?>" />
		    			<?php } ?>
					</div>
					<div style="float:left;vertical-align:middle;">
						<?php if(!empty($linkElm["image"])){ ?>
		    				<label>
		    					<input type="checkbox" name="l-e-f-d-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" value="<?php echo $checkbox; ?>" /> Smazat 
		    					<input type="hidden" value="<?php echo $linkElm["image"]; ?>" name="l-e-f-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" />
		    				</label>
		    			<?php }else{ ?>
	    					<input type="hidden" value="" name="l-e-f-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" />
	    				<?php } ?>
						<div style="margin-bottom:5px;"><span class="btn btn-default btn-file"><span class="fileinput-new">Vyberte obrázek</span><span class="fileinput-exists">Vyměnit</span><input type="file" name="l-e-file-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]"></span></div>
						<div><a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Odstranit</a></div>
					</div>
				</div>
				<div class="form-group" >
					<div class="checkbox" >
						<label><input class="create-sublink" <?php if($linkElm["isSublink"])echo"checked"; ?> type="checkbox" name="l-e-isSublink-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $checkbox; ?>" value="<?php echo $checkbox; ?>"/> Automaticky vytvořit pododkaz</label>
					</div>
				</div>
				<div class="form-group url" <?php if($linkElm["isSublink"])echo'style="display:none"'; ?>>
			    		    		
			    	<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    		<input value="<?php echo $linkElm["url"][$val->suffix] ?>" class="form-control url" placeholder="url" type="text" name="l-e-url-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>[]"/>
				    	</span>
			    	<?PHP $i++; } ?>
					<?php echo $this->render("languageMutations.phtml"); ?>
			    	
		    	</div>
			    <div class="form-group">
			    	
			    	<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    		<input value="<?php echo $linkElm["h2"][$val->suffix] ?>" class="form-control" placeholder="h2 nadpis" type="text" name="l-e-h2-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>[]"/>
				    	</span>
			    	<?PHP $i++; } ?>
					<?php echo $this->render("languageMutations.phtml"); ?>
		
			    </div>
			    <div class="form-group">
			    	
			    	<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
							<?php $rand = rand(0,100); ?>
			    			<textarea id="l-e-text-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>-<?php echo $rand; ?>" class="form-control tiny" placeholder="zprava" name="l-e-text-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>[]" ><?php echo $linkElm["text"][$val->suffix] ?></textarea>
			    			<script>execTinyMCE(1,'l-e-text-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>-<?php echo $rand; ?>');</script>
			    		</span>	
			    	<?PHP $i++; } ?>
					<?php echo $this->render("languageMutations.phtml"); ?>	    	
			    </div>
			    <input value="<?php echo $linkElm["linkID"]; ?>" type="hidden" name="l-e-linkID-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" />
	    	</div>  
    	<?php $checkbox++; } ?>	    
    </div>
    <div class="panel-footer">
    	<a class="btn btn-primary btn-xs add-link-element" href="#" title="Přidat element">Přidat element</a>
    	<input type="hidden" name="l-e-c-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>" value="<?php echo ($checkbox-1); ?>" />
    </div>
</div><input type="hidden" name="is-element-<?php echo $this->secI; ?>[]" value="l-<?php echo $this->elSecCount[$this->elementPriority] ?>" /></li>
