<li>
<div class="panel panel-default">
<div class="panel-heading clearfix">
	<span class="label label-dark-fosfor">Map element</span>
	<span class="glyphicons glyphicons-remove map-element" data="<?php echo $this->elementData["map"]["sectionID"]; ?>-<?php echo $this->elementData["map"]["groupLinkID"] ?>"></span>
	<span class="glyphicons glyphicons-move"></span>
	<span class="element-width form-inline">
		<label>Šířka elementu:</label>
		<select class="form-control" name="m-e-element-width-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>">
			<option <?php if($this->elementData["map"]['elementWidth'] == 12) echo "selected = 'selected'"?> value="12">12 dílů (celá šířka)</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 11) echo "selected = 'selected'"?>  value="11">11 dílů</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 10) echo "selected = 'selected'"?>  value="10">10 dílů</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 9) echo "selected = 'selected'"?>  value="9">9 dílů</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 8) echo "selected = 'selected'"?>  value="8">8 dílů</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 7) echo "selected = 'selected'"?>  value="7">7 dílů</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 6) echo "selected = 'selected'"?>  value="6">6 dílů (polovina šířky)</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 5) echo "selected = 'selected'"?>  value="5">5 dílů</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 4) echo "selected = 'selected'"?>  value="4">4 díly</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 3) echo "selected = 'selected'"?>  value="3">3 díly</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 2) echo "selected = 'selected'"?>  value="2">2 díly</option>
			<option <?php if($this->elementData["map"]['elementWidth'] == 1) echo "selected = 'selected'"?>  value="1">1 díl</option>
		</select>
	</span>
</div>
	<div class="panel-body">
    
    	<?php foreach($this->elementData["map"]["data"] as $mapElm){ ?>
    	    	
	    	<div class="clearfix row">
		    	<div class="col-sm-4">
		    		<div class="form-group">
		    	
			    		<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
							<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    			<input name="m-e-title-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>[]" value="<?php echo $mapElm["title"][$val->suffix] ?>" class="form-control" placeholder="nadpis" type="text"  />
				    		</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>
		    		
		    		</div>
		    	</div>
				<div class="col-xs-12 col-sm-4">
					<div class="form-group"><input value="<?php echo $mapElm["lat"] ?>" class="form-control" placeholder="souřadnice zeměpisné šířky" type="text" name="m-e-lat-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" /></div>
				</div>
		    	<div class="col-xs-12 col-sm-4">
		    		<div class="form-group"><input value="<?php echo $mapElm["long"] ?>" class="form-control" placeholder="souřadnice zeměpisné dély" type="text" name="m-e-long-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" /></div>
		    	</div>
	    	</div>
    	<?php } ?>
    </div>
    <div class="panel-footer">
    	<a class="btn btn-primary btn-xs add-map-element" href="#" title="Přidat element">Přidat element</a>
    </div>
</div>
<input type="hidden" name="is-element-<?php echo $this->secI; ?>[]" value="m-<?php echo $this->elSecCount[$this->elementPriority] ?>" />
</li>
