<script type="text/javascript" src="/Public/Jscripts/Bootstrap/jasny-bootstrap.js?2"></script>
<h1 class="font-weight-light mt-4"> Přidat odkaz </h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Obsah</li>
        <li class="breadcrumb-item active">Přidat odkaz</li>
    </ol>
</nav>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-4">
			<div class="card mb-4">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-show-thumbnails-with-lines pr-3 color-black"></span><span class="text">Obecný formulář</span>
        		</div>
        		<div class="card-body">
					<div class="form-group"> 		
						<label class="font-weight-bold d-block">Aktivní</label>						
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="active" id="active1" value="1" <?PHP if($this->active == 1 || !is_numeric($this->active))echo "checked='checked'" ?> /><label class="form-check-label" for="active1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="active" id="active2" value="0" <?PHP if($this->active == 0 && is_numeric($this->active))echo "checked='checked'" ?> /><label class="form-check-label" for="active2">Ne</label>
				    	</div>		    	
				    </div>
			    
					<div class="form-group">  			
						<label class="font-weight-bold d-block">Zobrazit v hlavičce</label>					
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inMenu" id="inMenu1" value="1" <?PHP if($this->inMenu == 1 || !is_numeric($this->inMenu))echo "checked='checked'" ?> /><label class="form-check-label" for="inMenu1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inMenu" id="inMenu2" value="0" <?PHP if($this->inMenu == 0 && is_numeric($this->inMenu))echo "checked='checked'" ?> /><label class="form-check-label" for="inMenu2">Ne</label>
				    	</div>	
				    </div>
			    
					<div class="form-group">  			
						<label class="font-weight-bold d-block">Zobrazit v patičce</label>			
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inFooter" id="inFooter1" value="1" <?PHP if($this->inFooter == 1)echo "checked='checked'" ?> /><label class="form-check-label" for="inFooter1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inFooter" id="inFooter2" value="0" <?PHP if($this->inFooter == 0)echo "checked='checked'" ?> /><label class="form-check-label" for="inFooter2">Ne</label>
				    	</div>	
			    	</div>
		
				    <div class="form-group">
				    	<label class="font-weight-bold d-block">Název odkazu</label>
				    	<div class="has-feedback position-relative">
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
						    		<input placeholder="Název odkazu" class="form-control" id="title" type="text" name="title-<?PHP echo $val->suffix ?>" value="<?php if($this->title[$val->suffix])echo $this->title[$val->suffix];?>" />
							    	<span class="requiere">*</span>
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?>
						</div> 
					</div>
					<div class="form-group"> 
						<label class="font-weight-bold d-block">Vlastní url</label>
						<div>
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					   			<input placeholder="Vlastní URL" class="form-control" type="text" name="otherLink-<?PHP echo $val->suffix ?>" value="<?php if($this->otherLink[$val->suffix])echo $this->otherLink[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div> 
					<div class="form-group">    
					    <label class="font-weight-bold d-block">Typ odkazu</label>
					    <select name="link-type" class="form-control">
					    	<option <?php if($this->linkType == 0)echo"selected"; ?> value="0"> Hlavní </option>
					    	<option <?php if($this->linkType == 1)echo"selected"; ?> value="1"> Subodkaz </option>
					    </select>
					</div> 
					<div <?php if(!$this->linkType)echo'class="sub-links"'; ?> >
						<div class="form-group"> 
					    	<label class="font-weight-bold d-block">Nadřazený odkaz</label>
						    <span id="selected-parent-link" class="selected-link" rel="0">
						    	<span class="value form-control v-0"><?PHP if($this->parentTitle)echo $this->parentTitle; else echo "&nbsp;"; ?></span>
							    <span class="parrent-links">
									<?PHP  echo $this->linksOutput ; ?>
							    </span>
						    	<input type="hidden" name="parent" value="<?PHP if($this->parent)echo $this->parent; else echo 0; ?>" id="selected-parent-input-0" />
						    </span>
						</div>
					</div>			
										
				</div>
			</div>
			
			<div class="card mb-4">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-note pr-3 color-black"></span><span class="text">SEO</span>
        		</div>
        		<div class="card-body">				
					<div class="form-group">
					 	<label class="font-weight-bold d-block">Odkaz na obsah stránky v předchozí verzi stránky:</label>	    
						<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    			<input class="form-control" id="oldUrl" type="text" name="oldUrl-<?PHP echo $val->suffix ?>" value="<?php if($this->oldUrl[$val->suffix])echo $this->oldUrl[$val->suffix];?>" />
							</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
				    </div> 	
			
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta nadpis</label>
						<div>
							<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
							    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<input placeholder="Meta nadpis" class="form-control" id="metaTitle" type="text" name="metaTitle-<?PHP echo $val->suffix ?>" value="<?php if($this->metaTitle[$val->suffix])echo $this->metaTitle[$val->suffix];?>" />
								</span>
							<?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div>
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta klíčová slova</label>
						<div>
							<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
							    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<input placeholder="Meta klíčová slova" class="form-control" id="keywords" type="text" name="keywords-<?PHP echo $val->suffix ?>" value="<?php if($this->keywords[$val->suffix])echo $this->keywords[$val->suffix];?>" />
								</span>
							<?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div>
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta popis</label>
						<div>
							<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
							    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    			<input placeholder="Meta popis" class="form-control" id="description" type="text" name="description-<?PHP echo $val->suffix ?>" value="<?php if($this->description[$val->suffix])echo $this->description[$val->suffix];?>" />
								</span>
							<?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
				    </div>
				
				</div>
			</div>
		</div>
		
		<div class="col-md-8">	
			<div class="card mb-4">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-sort pr-3 color-black"></span><span class="text">Sekce odkazu</span>
        		</div>
        		<div class="card-body">
					<div class="link-sections">
						<ul class="other-sections sortListBasic list-unstyled">
						
						</ul>
						<input class="section-count" type="hidden" name="section-count" value="0" />
					</div>
				</div>
				<div class="card-footer">
					<a class="btn btn-primary btn-xs add-section text-uppercase" href="#" title="Přidat sekci">přidat sekci</a>
				</div>
			</div>
		</div>
	
	</div>
	
	<div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block" type="submit" name="enter" value="Přidat" />
			</div>
		</div>
	</div>
</form>
    
