<li>
<div class="card mb-4">
<div class="card-header d-flex align-items-center">
<span class="badge badge-warning">Section header element</span>
<span class="element-width form-inline ml-auto mr-2">
	<label class="font-weight-bold mr-2">Šířka elementu:</label>
	<select class="form-control form-control-sm" name="s-h-e-element-width-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>">
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 12) echo "selected = 'selected'"?> value="12">12 dílů (celá šířka)</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 11) echo "selected = 'selected'"?>  value="11">11 dílů</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 10) echo "selected = 'selected'"?>  value="10">10 dílů</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 9) echo "selected = 'selected'"?>  value="9">9 dílů</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 8) echo "selected = 'selected'"?>  value="8">8 dílů</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 7) echo "selected = 'selected'"?>  value="7">7 dílů</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 6) echo "selected = 'selected'"?>  value="6">6 dílů (polovina šířky)</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 5) echo "selected = 'selected'"?>  value="5">5 dílů</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 4) echo "selected = 'selected'"?>  value="4">4 díly</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 3) echo "selected = 'selected'"?>  value="3">3 díly</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 2) echo "selected = 'selected'"?>  value="2">2 díly</option>
		<option <?php if($this->elementData["sectionHeader"]['elementWidth'] == 1) echo "selected = 'selected'"?>  value="1">1 díl</option>
	</select>
</span>
<span class="glyphicons glyphicons-move mr-2"></span>
<span class="glyphicons glyphicons-remove section-header" data="<?php echo $this->elementData["sectionHeader"]["sectionHeaderID"]; ?>"></span>
</div>
	<div class="card-body">
    	<div class="form-group">
    		<div class="row">
	    		<div class="col-xs-12 col-sm-6">
		    		<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
		    			<input name="s-h-e-h1-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>" value="<?php echo $this->elementData["sectionHeader"]["titleH1"][$val->suffix] ?>" class="form-control" placeholder="nadpis" type="text"  />
		    		</span>
					<?PHP $i++; } ?>
					<?php echo $this->render("languageMutations.phtml"); ?>   
				</div>
				<div class="col-xs-12 col-sm-6">
			    	<select class="form-control" name="s-h-e-h-type-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>">
			    		<option <?php if($this->elementData["sectionHeader"]["hType"] == "h1")echo "selected"; ?> value="h1">Nadpis H1</option>
			    		<option <?php if($this->elementData["sectionHeader"]["hType"] == "h2")echo "selected"; ?> value="h2">Nadpis H2</option>
			    	</select>
		    	</div>
			 	<div class="clearfix"></div>
		 	</div>	
        </div>
        <div class="form-group">
    		<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
			<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
    			<input name="s-h-e-h2-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>-<?php echo $val->suffix ?>" value="<?php echo $this->elementData["sectionHeader"]["titleH2"][$val->suffix] ?>" class="form-control" placeholder="popisek k nadpisu" type="text"  />
    		</span>
		<?PHP $i++; } ?>
		<?php echo $this->render("languageMutations.phtml"); ?>    		
        </div>

        <div class="radio">  
        	<div class="form-check form-check-inline">     	    	
    	    	<input value="center" class="form-check-input" <?php if($this->elementData["sectionHeader"]["align"] == "center")echo"checked"; ?> type="radio" name="s-h-e-align-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>" />
    	    	<label class="form-check-label">vycentrovat</label>
    	    </div>
        	<div class="form-check form-check-inline"> 
    	    	<input value="left" class="form-check-input" <?php if($this->elementData["sectionHeader"]["align"] == "left")echo"checked"; ?> type="radio" name="s-h-e-align-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>" />
    	    	<label class="form-check-label">zarovnat doleva</label>
    	    </div>
        	<div class="form-check form-check-inline"> 
    	    	<input value="right" class="form-check-input" <?php if($this->elementData["sectionHeader"]["align"] == "right")echo"checked"; ?> type="radio" name="s-h-e-align-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>" />
    	    	<label class="form-check-label">zarovnat doprava</label>
    	    </div>    	
    	</div>
	</div>
</div>
<input type="hidden" name="is-element-<?php echo $this->secI; ?>[]" value="sh-<?php echo $this->elSecCount[$this->elementPriority] ?>" />
</li>