<script type="text/javascript" src="/Public/Jscripts/Bootstrap/jasny-bootstrap.js?2"></script>
<h1 class="font-weight-light mt-4"> Upravit odkaz </h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Obsah</li>
        <li class="breadcrumb-item active">Upravit odkaz</li>
    </ol>
</nav>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">
     
     <div class="row">	
		<div class="col-md-4">
			<div class="card mb-4">	
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-show-thumbnails-with-lines pr-3 color-black"></span><span class="text">Obecný formulář</span>
        		</div>
        		<div class="card-body">
					<div class="form-group"> 		
						<label class="font-weight-bold d-block">Aktivní</label>						
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="active" id="active1" value="1" <?PHP if($this->allItems->active == 1)echo "checked='checked'" ?> /><label class="form-check-label" for="active1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="active" id="active2" value="0" <?PHP if($this->allItems->active == 0)echo "checked='checked'" ?> /><label class="form-check-label" for="active2">Ne</label>
				    	</div>		    	
				    </div>
			    
					<div class="form-group">  			
						<label class="font-weight-bold d-block">Zobrazit v hlavičce</label>					
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inMenu" id="inMenu1" value="1" <?PHP if($this->allItems->inMenu == 1)echo "checked='checked'" ?> /><label class="form-check-label" for="inMenu1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inMenu" id="inMenu2" value="0" <?PHP if($this->allItems->inMenu == 0)echo "checked='checked'" ?> /><label class="form-check-label" for="inMenu2">Ne</label>
				    	</div>	
				    </div>
			    
					<div class="form-group">  			
						<label class="font-weight-bold d-block">Zobrazit v patičce</label>			
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inFooter" id="inFooter1" value="1" <?PHP if($this->allItems->inFooter == 1)echo "checked='checked'" ?> /><label class="form-check-label" for="inFooter1">Ano</label>
				    	</div>				    	
				    	<div class="form-check form-check-inline">
				    		<input class="form-check-input" type="radio" name="inFooter" id="inFooter2" value="0" <?PHP if($this->allItems->inFooter == 0)echo "checked='checked'" ?> /><label class="form-check-label" for="inFooter2">Ne</label>
				    	</div>	
			    	</div>
		
				    <div class="form-group">
				    	<label class="font-weight-bold d-block">Název odkazu</label>
				    	<div class="has-feedback position-relative">
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
						    		<input placeholder="Název odkazu" class="form-control" id="title" type="text" name="title-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->title[$val->suffix])echo $this->allItems->title[$val->suffix];?>" />
							    	<span class="requiere">*</span>
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?>
						</div> 
					</div>
					<div class="form-group"> 
						<label class="font-weight-bold d-block">Vlastní url</label>
						<div>
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					   			<input placeholder="Vlastní URL" class="form-control" type="text" name="otherLink-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->otherLink[$val->suffix])echo $this->allItems->otherLink[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div> 
					<div class="form-group">    
					    <label class="font-weight-bold d-block">Typ odkazu</label>
					    <select name="link-type" class="form-control">
					    	<option <?php if($this->allItems->parentID == 0)echo"selected"; ?> value="0"> Hlavní </option>
					    	<option <?php if($this->allItems->parentID == 1)echo"selected"; ?> value="1"> Subodkaz </option>
					    </select>
					</div> 				    
					<div class="sub-links" <?php if($this->allItems->parentID)echo'style="display:block"'; ?> >
						<div class="form-group"> 
					    	<label class="font-weight-bold d-block">Nadřazený odkaz</label>
						    <span id="selected-parent-link" class="selected-link" rel="0">
						    	<span class="value form-control v-0"><?PHP if($this->parentTitle)echo $this->parentTitle; else echo "&nbsp;"; ?></span>
							    <span class="parrent-links">
									<?PHP  echo $this->linksOutput ; ?>
							    </span>
						    	<input type="hidden" name="parent" value="<?PHP if($this->allItems->parentID)echo $this->allItems->parentID; else echo 0; ?>" id="selected-parent-input-0" />
						    </span>
						</div>
					</div>
												
				</div>
			</div>			
			
			<div class="card mb-4">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-note pr-3 color-black"></span><span class="text">SEO</span>
        		</div>
        		<div class="card-body">	
					<div class="form-group">
					 	<label class="font-weight-bold d-block">Odkaz na obsah stránky v předchozí verzi stránky:</label>	  
						<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    <span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
				    			<input class="form-control" id="oldUrl" type="text" name="oldUrl-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems->oldUrl[$val->suffix])echo $this->allItems->oldUrl[$val->suffix];?>" />
							</span>
						<?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?> 
				    </div>
				
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta nadpis</label>
						<div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<input placeholder="Meta nadpis" class="form-control" id="metaTitle" type="text" name="metaTitle-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->metaTitle[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div>
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta klíčová slova</label>
						<div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
									<input placeholder="Meta klíčová slova" class="form-control" id="keywords" type="text" name="keywords-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->keywords[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
					</div>
					<div class="form-group">
						<label class="font-weight-bold d-block">Meta popis</label>
						<div>
						    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
						    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
					    			<input placeholder="Meta popis" class="form-control" id="description" type="text" name="description-<?PHP echo $val->suffix ?>" value="<?php echo $this->allItems->description[$val->suffix];?>" />
							    </span>
						    <?PHP $i++; } ?>
							<?php echo $this->render("languageMutations.phtml"); ?> 
						</div>
				    </div>
				
				</div>
			</div>
		</div>
		
		<div class="col-md-8">	
			<div class="card mb-4">		
        		<div class="card-header d-flex align-items-center">
        			<span class="glyphicons glyphicons-sort pr-3 color-black"></span><span class="text">Sekce odkazu</span>
        		</div>
        		<div class="card-body">
					<div class="link-sections">
						<ul class="other-sections sortListBasic list-unstyled">
							<?php $this->secI = 1; foreach($this->updateSectionData as $linkSectionID => $this->usd){ ?>
								<li>
								<div class="card mb-4">
								    <div class="card-header d-flex align-items-center">Sekce <span data="<?php echo $linkSectionID ?>" class="glyphicons glyphicons-move ml-auto mr-2"></span> <span class="glyphicons glyphicons-remove section"></span> </div>
								    <div class="card-body">
										<section data="<?php echo $this->secI; ?>">	
											<div class="row">
												<div class="col-sm-4 col-xs-12">
													<div class="form-group">
        												<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
        													<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix ?>" >
        										    			<input placeholder="název sekce" value="<?php echo $this->usd["option"]["name"][$val->suffix] ?>" type="text" name="sec-name-<?php echo $this->secI; ?>-<?PHP echo $val->suffix ?>" class="form-control">
        										    		</span>
        												<?PHP $i++; } ?>
        												<?php echo $this->render("languageMutations.phtml"); ?>
													</div>
												</div>
		    									<div class="col-sm-4 col-xs-12">
													<div class="form-group">
											    		<select name="sec-bg-color-<?php echo $this->secI; ?>" class="form-control">
											    			<option value="0"> bez barvy pozadí </option>
											    			<option value="grey" <?php if($this->usd["option"]["bgColor"] == "grey")echo "selected" ?> > šedé pozadí </option>
											    			<option value="white" <?php if($this->usd["option"]["bgColor"] == "white")echo "selected" ?> > bílé pozadí </option>
											    			<option value="black" <?php if($this->usd["option"]["bgColor"] == "black")echo "selected" ?> > černé pozadí </option>
											    			
											    		</select>
											    	</div>	
										    	</div>
										    	<div class="col-sm-4 col-xs-12">
													<div class="form-group">
    										    	    <label class="font-weight-bold d-block">Na celou šířku webu:</label>
    										    		<div class="form-check form-check-inline"><input <?php if($this->usd["option"]["wide"] == 1)echo "checked" ?> id="wide-<?php echo $this->secI; ?>1" type="radio" value="1" name="wide-<?php echo $this->secI; ?>" class="form-check-input" /><label  class="form-check-label" for="wide-<?php echo $this->secI; ?>1"> Ano </label></div>
    										    	    <div class="form-check form-check-inline"><input <?php if($this->usd["option"]["wide"] == 0)echo "checked" ?> id="wide-<?php echo $this->secI; ?>2" type="radio" value="0" name="wide-<?php echo $this->secI; ?>" class="form-check-input" /><label  class="form-check-label" for="wide-<?php echo $this->secI; ?>2"> Ne </label></div>
											    	</div>	
											    </div>
									    	</div>
											<div class="form-group section-control">														
    											<div class="dropdown">
    											  <button class="btn text-uppercase btn-block btn-primary" id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    											     --- vyberte element který chcete přidat do sekce --- 
    											  </button>
    											  <div class="dropdown-menu" aria-labelledby="dLabel">	  	
    											    <a data-elmtype="e-1" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="element obsahující pouze velký obrázek a text k němu">Header element</a>
    											    <a data-elmtype="e-2" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="nadpis jednotlivé sekce">Section Header element</a>
    											    <a data-elmtype="e-3" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="tvoří sloupce sekce a obsahuje fotku nadpis a text">Link element</a>
    											    <!-- <a data-elmtype="e-4" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="tak samo jako link element ale bez fotky a je propojený s jiným odkazem">Sublink element</a> -->
    											    <a data-elmtype="e-5" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="vložení textu do sekce">Text element</a>
    											    <!-- <a data-elmtype="e-6" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="vložení tabulky s filtrovaným seznamem">List element</a> -->
    											    <a data-elmtype="e-7" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="vložení formuláře">Form element</a>
    											    <a data-elmtype="e-8" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="vložení youtube nebo vimeo videí">YouTube,Vimeo element</a>
    											    <a data-elmtype="e-9" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="V tomto elementu se budou zobrazovat články, které přiřadíte tomuto odkazu vsekci Přidat článek">Element zobrazení článků</a>
    											    <a data-elmtype="e-10" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="V tomto elementu se budou zobrazovat vložené fotky nebo soubory">Element fotky a soubory</a>
    											    <a data-elmtype="e-11" class="dropdown-item d-flex align-items-center" href="" data-toggle="tooltip" data-placement="left" title="Element zobrazí googlemapu a jednolitvé body v ní">Map element</a>
    											  </div>
    											  <script>
    											  	$(function () {
    												  $('[data-toggle="tooltip"]').tooltip()
    												})
    											  </script>
    											</div>
    										</div>
										    
										    <?php $listCount = $mCount = $formCount = $sublinkCount = $linkCount = $textCount = $sectionHeaderCount = $headerCount = $ytvCount = $aCount = $phCount = 0 ?>
										    					
											<ul class="section-elements sortListBasic list-unstyled">
											
												<?php foreach($this->usd["elements"] as $this->elementPriority => $this->elementData){ ?>
												
													<?php if(!empty($this->elementData["header"])){ ?>	
														<?php 
															$headerCount++;
															$this->elSecCount[$this->elementPriority] = $headerCount;
														 	echo $this->render("odkazy/header-element.phtml"); 
														 ?>
													<?php } ?>	
													
													<?php if(!empty($this->elementData["sectionHeader"])){ ?>	
														<?php 
															$sectionHeaderCount++;
															$this->elSecCount[$this->elementPriority] = $sectionHeaderCount;
															echo $this->render("odkazy/section-header-element.phtml");
														?>
													<?php } ?>
													
													<?php if(!empty($this->elementData["linkElement"])){ ?>
														<?php 
															$linkCount++;
															$this->elSecCount[$this->elementPriority] = $linkCount;
															echo $this->render("odkazy/link-element.phtml"); 
														?>
													<?php } ?>
													
													<?php if(!empty($this->elementData["sublinkElement"])){ ?>
														<?php 
															$sublinkCount++;
															$this->elSecCount[$this->elementPriority] = $sublinkCount;
															echo $this->render("odkazy/sublink-element.phtml"); 
														?>
													<?php } ?>
													
													<?php if(!empty($this->elementData["textElement"])){ ?>	
														<?php 
															$textCount++;
															$this->elSecCount[$this->elementPriority] = $textCount;
															echo $this->render("odkazy/text-element.phtml"); 
														?>
													<?php } ?>
													<?php if(!empty($this->elementData["formElement"])){ ?>
														<?php 
															$formCount++;
															$this->elSecCount[$this->elementPriority] = $formCount;
															echo $this->render("odkazy/form-element.phtml"); 
														?>
													<?php } ?>
													<?php if(!empty($this->elementData["listElement"])){ ?>
														<?php 
															$listCount++;
															$this->elSecCount[$this->elementPriority] = $listCount;
															echo $this->render("odkazy/list-element.phtml"); 
														?>
													<?php } ?>	
													<?php if(!empty($this->elementData["ytvElement"])){ ?>
														<?php 
															$ytvCount++;
															$this->elSecCount[$this->elementPriority] = $ytvCount;
															echo $this->render("odkazy/ytv-element.phtml"); 
														?>
													<?php } ?>
													<?php if(!empty($this->elementData["article"])){ ?>
														<?php 
															$aCount++;
															$this->elSecCount[$this->elementPriority] = $aCount;
															echo $this->render("odkazy/article-element.phtml"); 
														?>
													<?php } ?>
													<?php if(!empty($this->elementData["photoFile"])){ ?>
														<?php 
															$phCount++;
															$this->elSecCount[$this->elementPriority] = $phCount;
															echo $this->render("odkazy/photo-file-element.phtml"); 
														?>
													<?php } ?>
													<?php if(!empty($this->elementData["map"])){ ?>
														<?php 
															$mCount++;
															$this->elSecCount[$this->elementPriority] = $mCount;
															echo $this->render("odkazy/map-element.phtml"); 
														?>
													<?php } ?>
												<?php } ?>	
																
										    </ul>
										    <input type="hidden" name="header-element-count-<?php echo $this->secI ?>" value="<?php echo $headerCount ?>" />
										    <input type="hidden" name="section-header-element-count-<?php echo $this->secI ?>" value="<?php echo $sectionHeaderCount ?>" />
										    <input type="hidden" name="link-element-count-<?php echo $this->secI ?>" value="<?php echo $linkCount ?>" />
										    <input type="hidden" name="sublink-element-count-<?php echo $this->secI ?>" value="<?php echo $sublinkCount ?>" />
										    <input type="hidden" name="list-element-count-<?php echo $this->secI ?>" value="<?php echo $listCount ?>" />
										    <input type="hidden" name="text-element-count-<?php echo $this->secI ?>" value="<?php echo $textCount ?>" />
		    	    		                <input type="hidden" name="form-element-count-<?php echo $this->secI ?>" value="<?php echo $formCount ?>" />
		    	    		                <input type="hidden" name="ytv-element-count-<?php echo $this->secI ?>" value="<?php echo $ytvCount ?>" />
		    	    		                <input type="hidden" name="article-element-count-<?php echo $this->secI ?>" value="<?php echo $aCount ?>" />
		    	    		                <input type="hidden" name="photo-file-element-count-<?php echo $this->secI ?>" value="<?php echo $phCount ?>" />
											<input type="hidden" name="map-element-count-<?php echo $this->secI ?>" value="<?php echo $mCount ?>" />
										</section>
										<input type="hidden" name="is-section[]" value="<?php echo $this->secI; ?>" />
									</div>							
								</div>
								</li>
							<?php $this->secI++; } ?>
						</ul>
						<input class="section-count" type="hidden" name="section-count" value="<?php echo $this->secI-1; ?>" />
					</div>
				</div>
				<div class="card-footer">
					<a class="btn btn-primary btn-xs add-section text-uppercase" href="#" title="Přidat sekci">přidat sekci</a>
				</div>
			</div>
		</div>
    </div>  
    <div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block" type="submit" name="enter" value="Upravit" />
			</div>
		</div>
	</div>
	
</form>
