<li>
<div class="panel panel-default">
	<div class="panel-heading clearfix"><span class="label label-brown">YoutTube,Vimeo element</span>
	<span class="glyphicons glyphicons-remove ytv-element" data="<?php echo $this->elementData["ytvElement"]["ytvID"] ?>"></span>
	<span class="glyphicons glyphicons-move"></span>	
    <span class="element-width form-inline">
    	<label>Šířka elementu:</label>
    	<select class="form-control" name="ytv-element-width-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>">
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 12) echo "selected = 'selected'"?> value="12">12 dílů (celá šířka)</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 11) echo "selected = 'selected'"?> value="11">11 dílů</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 10) echo "selected = 'selected'"?> value="10">10 dílů</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 9) echo "selected = 'selected'"?>  value="9">9 dílů</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 8) echo "selected = 'selected'"?>  value="8">8 dílů</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 7) echo "selected = 'selected'"?>  value="7">7 dílů</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 6) echo "selected = 'selected'"?>  value="6">6 dílů (polovina šířky)</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 5) echo "selected = 'selected'"?>  value="5">5 dílů</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 4) echo "selected = 'selected'"?>  value="4">4 díly</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 3) echo "selected = 'selected'"?>  value="3">3 díly</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 2) echo "selected = 'selected'"?>  value="2">2 díly</option>
    		<option <?php if($this->elementData["ytvElement"]['elementWidth'] == 1) echo "selected = 'selected'"?>  value="1">1 díl</option>
    	</select>
    </span>
</div>
	<div class="panel-body">
    
    	<?php $checkbox = 1; foreach($this->elementData["ytvElement"]["data"] as $ytvElm){ ?>
    			<div class="clearfix">
    			<div class="col-xs-6">	
					<div class="form-group">	
						     	
		    		<?php if($ytvElm["type"] == "youtube"){ ?>
		    			<iframe style="display:inline-block;vertical-align: middle;" width="200" height="50" src="http://www.youtube.com/embed/<?php echo $ytvElm["code"] ?>" frameborder="0" allowfullscreen></iframe>
		    			<input value="https://www.youtube.com/watch?v=<?php echo $ytvElm["code"] ?>" type="hidden" name="ytv-element-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" />		
		    		<?php }else{ ?>
		    			<iframe style="display:inline-block;vertical-align: middle;" src="http://player.vimeo.com/video/<?php echo $ytvElm["code"] ?>?title=0&amp;byline=0&amp;portrait=0" width="200" height="50" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
		    			<input value="http://player.vimeo.com/video/<?php echo $ytvElm["code"] ?>" type="hidden" name="ytv-element-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" />
		    		<?php } ?>
		    		
		    		<label class="checkbox-inline"><input type="checkbox" name="ytv-delete-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]" value="<?php echo $checkbox; ?>" /> smazat</label>
		    		
		    	</div>
			</div>
			
			<?php if(count($this->allCategories) > 0){ ?>
			<div class="col-xs-6">
				<div class="form-group">	    	
			    	<select class="form-control" name="ytv-c-element-<?php echo $this->secI ?>-<?php echo $this->elSecCount[$this->elementPriority] ?>[]">
			    		<option value="0"> -- vyberte kategorii -- </option>
			    		<?php foreach($this->allCategories as $cat){ ?>				    		
			    			<option <?php if($ytvElm["categoryID"] == $cat->categoryID)echo "selected"; ?> value="<?php echo $cat->categoryID; ?>"> <?php echo $cat->title; ?> </option>
			    		<?php } ?>
			    	</select>
			    </div>
			</div>
			<?php } ?>
			</div>
		<?php $checkbox++; } ?>
	</div>
	<div class="panel-footer">
		<a class="btn btn-primary btn-xs add-ytv-element" href="#" title="Přidat video">Přidat video</a>
	</div>
</div><input type="hidden" name="is-element-<?php echo $this->secI; ?>[]" value="ytv-<?php echo $this->elSecCount[$this->elementPriority] ?>" />
</li>
