<h1> Seznam filtrů </h1>

<ol class="breadcrumb">
	<li>Eshop</li>
	<li class="active">Seznam filtrů</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="" method="post">
	<div class="panel panel-default">		
		<div class="panel-heading clearfix">
			
				<div class="row">
					<div class="col-sm-6">
						<a class="btn btn-sm btn-success delButton" href="/admin/eshop/filtry/pridat"> Přidat nový filtr </a>
					</div>
					<div class="text-right col-sm-6">
					<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
					</div>
				</div>
			
		</div>
		<div class="panel-body table-responsive">
		
			<div class="clearfix data-list header">
				<div class="col-sm-6 no-left-padding th">Název barvy</div>
				<div class="col-sm-6 text-right th">upravit / smazat</div>		
			</div>
			
			<?php if(count($this->allItems) > 0){ ?>	
			    <ul class="sortListBasic data-list main-ul filter">
					<?php foreach($this->allItems as $val){ ?>
					        <li class="clearfix" id="<?php echo $val->filterID ?>">               
								<div class="col-sm-6 first-col text-overflow" ><span class="glyphicons glyphicons-move"></span> <?php echo $val->title; ?></div>
								<div class="col-sm-6 text-right">
								    <a title="<?PHP echo $this->translate('Uprav'); ?>" href="<?php echo $this->baseUrl; ?>/admin/eshop/filtry/upravit/id/<?php echo $val->filterID?>"><span class="glyphicons glyphicons-pencil"></span></a>   
								    <input class="delete" type="checkbox" name="delete[]" value="<?php echo $val->filterID ?>">
								</div>
								
								<br id="endFloat" />
			                
			                </li>
					<?php } ?>
				</ul>
			<?php }else{ ?>
				<div class="no-data text-center">Zatím se zde nenachází žádný filtr.</div>
			<?php } ?>
			
				
		</div>	
		<div class="panel-footer clearfix">
			
			<div class="text-right">
				<button type="button" class="btn btn-sm btn-danger delButton"> Smazat označené </button>
				<input type="submit" class ="hidden deleteButton" name="deleteButton" />
			</div>
			
		</div>	
	</div>
</form>