<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
	
	<head>
		<title><?PHP echo $this->headTitle ?></title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="keywords" content="<?PHP echo $this->headKeyWords ?>" />
		<meta name="description" content="<?PHP echo $this->headDescription ?>" />
		<meta name="robots" content="index,follow" />
		<meta name="author" content="1vision.cz" />

		<link href="/Public/Images/Layout/favicon.png" rel="shortcut icon" />
		<link rel="stylesheet" type="text/css" href="/Public/Css/error.css" />
		<!--  jAlert -->
	    <!--<link rel="stylesheet" type="text/css" href="/Public/Jscripts/JqueryAlerts/jquery.alerts.css" media="screen" />-->
		<!-- fancybox -->
		<link rel="stylesheet" href="/Public/Jscripts/Fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
		
		<script type="text/javascript" src = "/Public/Jscripts/WebBase/jquery-latest.js"></script>
		<script type="text/javascript" src = "/Public/Jscripts/WebBase/events.js"></script>
		<script type="text/javascript" src = "/Public/Jscripts/Web/events.js"></script>
		<!--<script type="text/javascript" src = "/Public/Jscripts/AdminBase/quicksearch.js"></script> -->
		<script type="text/javascript" src = "/Public/Jscripts/WebBase/cycle.js"></script>
		<!--<script type="text/javascript" src = "/Public/Player/swfobject.js"></script>-->
		<!--  jAlert -->
		<!--<script type="text/javascript" src = "/Public/Jscripts/JqueryAlerts/jquery.alerts.js"></script>-->
		
		<!-- fancybox -->
		<script type="text/javascript" src="/Public/Jscripts/Fancybox/jquery.fancybox-1.3.4.js"></script>
		<script type="text/javascript" src="/Public/Jscripts/Fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
		
	</head>	
	
	<body>	 
		<div id="container">
  			<div id="header">
  				
  				  				
  			</div><!-- end div#header -->			
  			
  			<div id="content">
	  			 
	  			<img src="/Public/Images/Admin/warning.png" /> 
				<h2>Jejda, tato stránka bohužel neexistuje.</h2> 
				<p>Pokračujte prosím na úvodní stránku, a to <a href="/">ZDE</a>.</p>
	  			
  			</div><!-- end div#content --> 			
  			
  			 
          </div><!-- end div#container -->
          <div id="footer">	
              
  		  </div><!-- end div#footer -->
	</body>
</html>
