
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title> <?php echo $this->headTitle; ?> </title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl ?>/Public/Css/noie6.css" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="robots" content="index,follow" />
	<meta name="description" content="Internetový komunikační­ portál eCENTRE, a.s." />		
	<meta name="keywords" content="elektronická výběrová řízení,elektronická aukce, systém združených nákupů,úspora nákladů" />		
	<meta name="author" content="POLAR televize Ostrava, s.r.o."/>
	<link rel="shortcut icon"  href="/Public/Images/favicon.ico" />

   
</head>
<body>
    <p><img src="/Public/Images/Layout/logo.png" /></p>
    <p>Je nám líto, ale tyto stránky nepodporují zastaralý prohlížeč Internet Explorer <?php echo $this->version; ?>.0</p>
    <p>Doporučujeme Vám stáhnout si novější verzi <a href="http://www.microsoft.com/cze/windows/internet-explorer/worldwide-sites.aspx">Internet Exploreru</a> a nebo jiný prohlížeč, například <a href="http://www.google.com/chrome"> Google Chrome </a></p>
</body>
</html>
