<h1 class="font-weight-light mt-4"> Sociální sítě</h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Patička</li>
        <li class="breadcrumb-item active">Sociální sítě</li>
    </ol>
</nav>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">	
		<div class="col-md-12">
			<div class="card">
				<div class="card-header d-flex align-items-center">Ikony</div>				
				<div class="card-body">		
    				<table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col" class="text-left">Ikona</th>
                          <th scope="col" class="text-center">Název</th>
                          <th scope="col" class="text-center">Zobrazit ikonu</th>
                          <th scope="col" class="text-center">URL adresa</th>
                        </tr>
                      </thead>
                      <tbody class="sortListBasic data-list main-ul socialIcons">
    					
    					<?php if(count($this->allItems) > 0){ ?>	
    							<?php foreach($this->allItems as $item){ ?>
    					                <tr id="<?php echo $item->socialIconsID ?>">
                                          <td class="text-left align-middle"><span class="glyphicons glyphicons-move mr-2"></span> <span class="social social-<?php echo $item->icon?>"></span></td>
                                          <td class="text-center align-middle"><?php echo $item->title; ?></td>
                                          <td class="text-center align-middle">
    										<div class="form-check form-check-inline">
                    				    		<input id="showIcon<?php echo $item->socialIconsID?>1" type="radio" value="1" <?PHP if($item->showIcon == 1)echo "checked='checked'"; ?> name="showIcon<?php echo $item->socialIconsID?>" class="form-check-input"><label class="form-check-label" for="showIcon<?php echo $item->socialIconsID?>1">Ano</label>
                    				    	</div>
                				    		<div class="form-check form-check-inline">
                    				    		<input id="showIcon<?php echo $item->socialIconsID?>2" type="radio" value="0" <?PHP if($item->showIcon == 0)echo "checked='checked'"; ?> name="showIcon<?php echo $item->socialIconsID?>" class="form-check-input"><label class="form-check-label" for="showIcon<?php echo $item->socialIconsID?>2">Ne</label>
                    				    	</div>
    									  </td>
                                          <td class="text-right align-middle">
                                              <div>
                                          		<?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
        									    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
        										    	<input class="form-control text" type="text" name="url<?php echo $item->socialIconsID;?>-<?PHP echo $val->suffix ?>" value="<?php if($item->url[$val->suffix])echo $item->url[$val->suffix];?>" />
        										    </span>
        									    <?PHP $i++; } ?>
        										<?php echo $this->render("languageMutations.phtml"); ?>  
                            				  </div>
                        				  </td>
                                        </tr>
    							<?php } ?>
    						
    					<?php }else{ ?>
    						<tr class="no-data text-center"><td colspan="5">Zatím se zde nenachází žádné ikony.</td></tr>
    					<?php } ?>
                      </tbody>
                    </table>
				</div>	
			</div>	
		</div>
	</div>
	
	<div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block check-required-fields" type="submit" name="enter" value="Upravit" />
			</div>
		</div>
	</div>
</form>	
	
