<h1 class="font-weight-light mt-4"> Text v patičce</h1>

<nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb py-2 px-3">
        <li class="breadcrumb-item">Patička</li>
        <li class="breadcrumb-item active">Text</li>
    </ol>
</nav>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header d-flex align-items-center">Text v patičce</div>				
				<div class="card-body">
					 <div class="form-group has-feedback">	
					 	<label class="font-weight-bold d-block">Adresa:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
						    	<input class="form-control" type="text" name="text1-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems && !empty($this->allItems[1]) && $this->allItems[1]->text[$val->suffix])echo $this->allItems[1]->text[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				    
				    <div class="form-group has-feedback">	
					 	<label class="font-weight-bold d-block">Email:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
						    	<input class="form-control" type="text" name="text2-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems && !empty($this->allItems[2]) && $this->allItems[2]->text[$val->suffix])echo $this->allItems[2]->text[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				    
				    <div class="form-group has-feedback">	
					 	<label class="font-weight-bold d-block">Tel:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
						    	<input class="form-control" type="text" name="text3-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems && !empty($this->allItems[3]) && $this->allItems[3]->text[$val->suffix])echo $this->allItems[3]->text[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				    
				</div>
			</div>			
		</div>	
	</div>
	
	<div class="card mt-4 mb-4">		
        <div class="card-body">
			<div class="col-sm-6 col-xs-12 offset-sm-3 offset-xs-0">
				<input class="btn btn-primary btn-block check-required-fields" type="submit" name="enter" value="Upravit" />
			</div>
		</div>
	</div>
</form>	
	
