<h1> Upravit sekci na hlavní stránce</h1>

<ol class="breadcrumb">
	<li>Extra obsah</li>
	<li class="active">Homepage - texty</li>
</ol>

<?php if($this->error !=''){ echo"<div class=\"alert alert-danger\">" .$this->error. "</div>";} ?>
<?php if($this->message !=''){ echo"<div class=\"alert alert-success\">" .$this->message. "</div>";} ?>

<form action="<?php echo $this->action ;?>" method="post" enctype="multipart/form-data">

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">Text v patičce</div>				
				<div class="panel-body">
					 <div class="form-group has-feedback">	
					 	<label>Adresa:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
						    	<input class="form-control" type="text" name="text1-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems && !empty($this->allItems[1]) && $this->allItems[1]->text[$val->suffix])echo $this->allItems[1]->text[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				    
				    <div class="form-group has-feedback">	
					 	<label>Email:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
						    	<input class="form-control" type="text" name="text2-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems && !empty($this->allItems[2]) && $this->allItems[2]->text[$val->suffix])echo $this->allItems[2]->text[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				    
				    <div class="form-group has-feedback">	
					 	<label>Tel:</label>	    	
					    <?PHP $i=0; foreach($this->allLanguageMutations as $val){ ?>
					    	<span class="language-input <?PHP if($i != 0)echo "hidden-lang "; echo $val->suffix  ?>" >
						    	<input class="form-control" type="text" name="text3-<?PHP echo $val->suffix ?>" value="<?php if($this->allItems && !empty($this->allItems[3]) && $this->allItems[3]->text[$val->suffix])echo $this->allItems[3]->text[$val->suffix];?>" />
						    </span>
					    <?PHP $i++; } ?>
						<?php echo $this->render("languageMutations.phtml"); ?>  
				    </div>
				    
				</div>
			</div>			
		</div>	
	</div>
	
	<div class="well">
		<div class="clearfix">
			<div class="col-sm-6 col-xs-12 col-sm-offset-3 col-xs-offset-0">
				<input class="btn btn-primary btn-block check-required-fields" type="submit" name="enter" value="Upravit" />
			</div>
		</div>
	</div>
</form>	
	
